// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//英雄
type Hero struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	HeroType             int32    `protobuf:"varint,2,opt,name=heroType,proto3" json:"heroType,omitempty"`
	Equips               []string `protobuf:"bytes,3,rep,name=equips,proto3" json:"equips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Hero) GetHeroType() int32 {
	if m != nil {
		return m.HeroType
	}
	return 0
}

func (m *Hero) GetEquips() []string {
	if m != nil {
		return m.Equips
	}
	return nil
}

//
//道具
type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Item) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

//
//装备
type Equip struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ItemId               int32    `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	HeroId               string   `protobuf:"bytes,3,opt,name=heroId,proto3" json:"heroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Equip) Reset()         { *m = Equip{} }
func (m *Equip) String() string { return proto.CompactTextString(m) }
func (*Equip) ProtoMessage()    {}
func (*Equip) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *Equip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Equip.Unmarshal(m, b)
}
func (m *Equip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Equip.Marshal(b, m, deterministic)
}
func (m *Equip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Equip.Merge(m, src)
}
func (m *Equip) XXX_Size() int {
	return xxx_messageInfo_Equip.Size(m)
}
func (m *Equip) XXX_DiscardUnknown() {
	xxx_messageInfo_Equip.DiscardUnknown(m)
}

var xxx_messageInfo_Equip proto.InternalMessageInfo

func (m *Equip) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Equip) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Equip) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

type AddHeroData struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	HeroType             []int32  `protobuf:"varint,2,rep,packed,name=heroType,proto3" json:"heroType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddHeroData) Reset()         { *m = AddHeroData{} }
func (m *AddHeroData) String() string { return proto.CompactTextString(m) }
func (*AddHeroData) ProtoMessage()    {}
func (*AddHeroData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *AddHeroData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHeroData.Unmarshal(m, b)
}
func (m *AddHeroData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHeroData.Marshal(b, m, deterministic)
}
func (m *AddHeroData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHeroData.Merge(m, src)
}
func (m *AddHeroData) XXX_Size() int {
	return xxx_messageInfo_AddHeroData.Size(m)
}
func (m *AddHeroData) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHeroData.DiscardUnknown(m)
}

var xxx_messageInfo_AddHeroData proto.InternalMessageInfo

func (m *AddHeroData) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddHeroData) GetHeroType() []int32 {
	if m != nil {
		return m.HeroType
	}
	return nil
}

type AddItemData struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ItemList             []*Item  `protobuf:"bytes,2,rep,name=itemList,proto3" json:"itemList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemData) Reset()         { *m = AddItemData{} }
func (m *AddItemData) String() string { return proto.CompactTextString(m) }
func (*AddItemData) ProtoMessage()    {}
func (*AddItemData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *AddItemData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemData.Unmarshal(m, b)
}
func (m *AddItemData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemData.Marshal(b, m, deterministic)
}
func (m *AddItemData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemData.Merge(m, src)
}
func (m *AddItemData) XXX_Size() int {
	return xxx_messageInfo_AddItemData.Size(m)
}
func (m *AddItemData) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemData.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemData proto.InternalMessageInfo

func (m *AddItemData) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddItemData) GetItemList() []*Item {
	if m != nil {
		return m.ItemList
	}
	return nil
}

type AddEquipData struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ItemIdx              []int32  `protobuf:"varint,2,rep,packed,name=itemIdx,proto3" json:"itemIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEquipData) Reset()         { *m = AddEquipData{} }
func (m *AddEquipData) String() string { return proto.CompactTextString(m) }
func (*AddEquipData) ProtoMessage()    {}
func (*AddEquipData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}

func (m *AddEquipData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEquipData.Unmarshal(m, b)
}
func (m *AddEquipData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEquipData.Marshal(b, m, deterministic)
}
func (m *AddEquipData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEquipData.Merge(m, src)
}
func (m *AddEquipData) XXX_Size() int {
	return xxx_messageInfo_AddEquipData.Size(m)
}
func (m *AddEquipData) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEquipData.DiscardUnknown(m)
}

var xxx_messageInfo_AddEquipData proto.InternalMessageInfo

func (m *AddEquipData) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddEquipData) GetItemIdx() []int32 {
	if m != nil {
		return m.ItemIdx
	}
	return nil
}

type OptionData struct {
	Part                 int32    `protobuf:"varint,1,opt,name=part,proto3" json:"part,omitempty"`
	Original             string   `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionData) Reset()         { *m = OptionData{} }
func (m *OptionData) String() string { return proto.CompactTextString(m) }
func (*OptionData) ProtoMessage()    {}
func (*OptionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}

func (m *OptionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionData.Unmarshal(m, b)
}
func (m *OptionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionData.Marshal(b, m, deterministic)
}
func (m *OptionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionData.Merge(m, src)
}
func (m *OptionData) XXX_Size() int {
	return xxx_messageInfo_OptionData.Size(m)
}
func (m *OptionData) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionData.DiscardUnknown(m)
}

var xxx_messageInfo_OptionData proto.InternalMessageInfo

func (m *OptionData) GetPart() int32 {
	if m != nil {
		return m.Part
	}
	return 0
}

func (m *OptionData) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

type OptionHeroEquip struct {
	Uuid                 string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	HeroId               string                 `protobuf:"bytes,2,opt,name=heroId,proto3" json:"heroId,omitempty"`
	List                 map[string]*OptionData `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OptionHeroEquip) Reset()         { *m = OptionHeroEquip{} }
func (m *OptionHeroEquip) String() string { return proto.CompactTextString(m) }
func (*OptionHeroEquip) ProtoMessage()    {}
func (*OptionHeroEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{7}
}

func (m *OptionHeroEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionHeroEquip.Unmarshal(m, b)
}
func (m *OptionHeroEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionHeroEquip.Marshal(b, m, deterministic)
}
func (m *OptionHeroEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionHeroEquip.Merge(m, src)
}
func (m *OptionHeroEquip) XXX_Size() int {
	return xxx_messageInfo_OptionHeroEquip.Size(m)
}
func (m *OptionHeroEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionHeroEquip.DiscardUnknown(m)
}

var xxx_messageInfo_OptionHeroEquip proto.InternalMessageInfo

func (m *OptionHeroEquip) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OptionHeroEquip) GetHeroId() string {
	if m != nil {
		return m.HeroId
	}
	return ""
}

func (m *OptionHeroEquip) GetList() map[string]*OptionData {
	if m != nil {
		return m.List
	}
	return nil
}

//英雄
type ResHero struct {
	Hero                 map[string]*Hero `protobuf:"bytes,1,rep,name=hero,proto3" json:"hero,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResHero) Reset()         { *m = ResHero{} }
func (m *ResHero) String() string { return proto.CompactTextString(m) }
func (*ResHero) ProtoMessage()    {}
func (*ResHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{8}
}

func (m *ResHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHero.Unmarshal(m, b)
}
func (m *ResHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHero.Marshal(b, m, deterministic)
}
func (m *ResHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHero.Merge(m, src)
}
func (m *ResHero) XXX_Size() int {
	return xxx_messageInfo_ResHero.Size(m)
}
func (m *ResHero) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHero.DiscardUnknown(m)
}

var xxx_messageInfo_ResHero proto.InternalMessageInfo

func (m *ResHero) GetHero() map[string]*Hero {
	if m != nil {
		return m.Hero
	}
	return nil
}

type HeroReply struct {
	Httpuuid             string   `protobuf:"bytes,1,opt,name=httpuuid,proto3" json:"httpuuid,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *ResHero `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeroReply) Reset()         { *m = HeroReply{} }
func (m *HeroReply) String() string { return proto.CompactTextString(m) }
func (*HeroReply) ProtoMessage()    {}
func (*HeroReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{9}
}

func (m *HeroReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroReply.Unmarshal(m, b)
}
func (m *HeroReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroReply.Marshal(b, m, deterministic)
}
func (m *HeroReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroReply.Merge(m, src)
}
func (m *HeroReply) XXX_Size() int {
	return xxx_messageInfo_HeroReply.Size(m)
}
func (m *HeroReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroReply.DiscardUnknown(m)
}

var xxx_messageInfo_HeroReply proto.InternalMessageInfo

func (m *HeroReply) GetHttpuuid() string {
	if m != nil {
		return m.Httpuuid
	}
	return ""
}

func (m *HeroReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HeroReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HeroReply) GetData() *ResHero {
	if m != nil {
		return m.Data
	}
	return nil
}

//道具
type ResItem struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResItem) Reset()         { *m = ResItem{} }
func (m *ResItem) String() string { return proto.CompactTextString(m) }
func (*ResItem) ProtoMessage()    {}
func (*ResItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{10}
}

func (m *ResItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResItem.Unmarshal(m, b)
}
func (m *ResItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResItem.Marshal(b, m, deterministic)
}
func (m *ResItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResItem.Merge(m, src)
}
func (m *ResItem) XXX_Size() int {
	return xxx_messageInfo_ResItem.Size(m)
}
func (m *ResItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ResItem.DiscardUnknown(m)
}

var xxx_messageInfo_ResItem proto.InternalMessageInfo

func (m *ResItem) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ItemReply struct {
	Httpuuid             string   `protobuf:"bytes,1,opt,name=httpuuid,proto3" json:"httpuuid,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *ResItem `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemReply) Reset()         { *m = ItemReply{} }
func (m *ItemReply) String() string { return proto.CompactTextString(m) }
func (*ItemReply) ProtoMessage()    {}
func (*ItemReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{11}
}

func (m *ItemReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemReply.Unmarshal(m, b)
}
func (m *ItemReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemReply.Marshal(b, m, deterministic)
}
func (m *ItemReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemReply.Merge(m, src)
}
func (m *ItemReply) XXX_Size() int {
	return xxx_messageInfo_ItemReply.Size(m)
}
func (m *ItemReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemReply.DiscardUnknown(m)
}

var xxx_messageInfo_ItemReply proto.InternalMessageInfo

func (m *ItemReply) GetHttpuuid() string {
	if m != nil {
		return m.Httpuuid
	}
	return ""
}

func (m *ItemReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ItemReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ItemReply) GetData() *ResItem {
	if m != nil {
		return m.Data
	}
	return nil
}

//装备
type ResEquip struct {
	Equips               map[string]*Equip `protobuf:"bytes,1,rep,name=equips,proto3" json:"equips,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResEquip) Reset()         { *m = ResEquip{} }
func (m *ResEquip) String() string { return proto.CompactTextString(m) }
func (*ResEquip) ProtoMessage()    {}
func (*ResEquip) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{12}
}

func (m *ResEquip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResEquip.Unmarshal(m, b)
}
func (m *ResEquip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResEquip.Marshal(b, m, deterministic)
}
func (m *ResEquip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResEquip.Merge(m, src)
}
func (m *ResEquip) XXX_Size() int {
	return xxx_messageInfo_ResEquip.Size(m)
}
func (m *ResEquip) XXX_DiscardUnknown() {
	xxx_messageInfo_ResEquip.DiscardUnknown(m)
}

var xxx_messageInfo_ResEquip proto.InternalMessageInfo

func (m *ResEquip) GetEquips() map[string]*Equip {
	if m != nil {
		return m.Equips
	}
	return nil
}

type EquipReply struct {
	Httpuuid             string    `protobuf:"bytes,1,opt,name=httpuuid,proto3" json:"httpuuid,omitempty"`
	Uuid                 string    `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 int32     `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *ResEquip `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EquipReply) Reset()         { *m = EquipReply{} }
func (m *EquipReply) String() string { return proto.CompactTextString(m) }
func (*EquipReply) ProtoMessage()    {}
func (*EquipReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{13}
}

func (m *EquipReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipReply.Unmarshal(m, b)
}
func (m *EquipReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipReply.Marshal(b, m, deterministic)
}
func (m *EquipReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipReply.Merge(m, src)
}
func (m *EquipReply) XXX_Size() int {
	return xxx_messageInfo_EquipReply.Size(m)
}
func (m *EquipReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipReply.DiscardUnknown(m)
}

var xxx_messageInfo_EquipReply proto.InternalMessageInfo

func (m *EquipReply) GetHttpuuid() string {
	if m != nil {
		return m.Httpuuid
	}
	return ""
}

func (m *EquipReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EquipReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EquipReply) GetData() *ResEquip {
	if m != nil {
		return m.Data
	}
	return nil
}

// 打开宝箱
type ResBox struct {
	Box                  []*Item  `protobuf:"bytes,1,rep,name=box,proto3" json:"box,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResBox) Reset()         { *m = ResBox{} }
func (m *ResBox) String() string { return proto.CompactTextString(m) }
func (*ResBox) ProtoMessage()    {}
func (*ResBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{14}
}

func (m *ResBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResBox.Unmarshal(m, b)
}
func (m *ResBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResBox.Marshal(b, m, deterministic)
}
func (m *ResBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResBox.Merge(m, src)
}
func (m *ResBox) XXX_Size() int {
	return xxx_messageInfo_ResBox.Size(m)
}
func (m *ResBox) XXX_DiscardUnknown() {
	xxx_messageInfo_ResBox.DiscardUnknown(m)
}

var xxx_messageInfo_ResBox proto.InternalMessageInfo

func (m *ResBox) GetBox() []*Item {
	if m != nil {
		return m.Box
	}
	return nil
}

func (m *ResBox) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type OpenBoxReply struct {
	Httpuuid             string   `protobuf:"bytes,1,opt,name=httpuuid,proto3" json:"httpuuid,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *ResBox  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenBoxReply) Reset()         { *m = OpenBoxReply{} }
func (m *OpenBoxReply) String() string { return proto.CompactTextString(m) }
func (*OpenBoxReply) ProtoMessage()    {}
func (*OpenBoxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{15}
}

func (m *OpenBoxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenBoxReply.Unmarshal(m, b)
}
func (m *OpenBoxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenBoxReply.Marshal(b, m, deterministic)
}
func (m *OpenBoxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenBoxReply.Merge(m, src)
}
func (m *OpenBoxReply) XXX_Size() int {
	return xxx_messageInfo_OpenBoxReply.Size(m)
}
func (m *OpenBoxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenBoxReply.DiscardUnknown(m)
}

var xxx_messageInfo_OpenBoxReply proto.InternalMessageInfo

func (m *OpenBoxReply) GetHttpuuid() string {
	if m != nil {
		return m.Httpuuid
	}
	return ""
}

func (m *OpenBoxReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OpenBoxReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *OpenBoxReply) GetData() *ResBox {
	if m != nil {
		return m.Data
	}
	return nil
}

//room+++++++++++++++++++++++++++++++++++++++++
//获取房间
type ReqGetRooms struct {
	Start                int32    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Len                  int32    `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetRooms) Reset()         { *m = ReqGetRooms{} }
func (m *ReqGetRooms) String() string { return proto.CompactTextString(m) }
func (*ReqGetRooms) ProtoMessage()    {}
func (*ReqGetRooms) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{16}
}

func (m *ReqGetRooms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetRooms.Unmarshal(m, b)
}
func (m *ReqGetRooms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetRooms.Marshal(b, m, deterministic)
}
func (m *ReqGetRooms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetRooms.Merge(m, src)
}
func (m *ReqGetRooms) XXX_Size() int {
	return xxx_messageInfo_ReqGetRooms.Size(m)
}
func (m *ReqGetRooms) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetRooms.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetRooms proto.InternalMessageInfo

func (m *ReqGetRooms) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ReqGetRooms) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type RespGetRooms struct {
	Httpuuid             string   `protobuf:"bytes,1,opt,name=httpuuid,proto3" json:"httpuuid,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *ResBox  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespGetRooms) Reset()         { *m = RespGetRooms{} }
func (m *RespGetRooms) String() string { return proto.CompactTextString(m) }
func (*RespGetRooms) ProtoMessage()    {}
func (*RespGetRooms) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{17}
}

func (m *RespGetRooms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGetRooms.Unmarshal(m, b)
}
func (m *RespGetRooms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGetRooms.Marshal(b, m, deterministic)
}
func (m *RespGetRooms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGetRooms.Merge(m, src)
}
func (m *RespGetRooms) XXX_Size() int {
	return xxx_messageInfo_RespGetRooms.Size(m)
}
func (m *RespGetRooms) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGetRooms.DiscardUnknown(m)
}

var xxx_messageInfo_RespGetRooms proto.InternalMessageInfo

func (m *RespGetRooms) GetHttpuuid() string {
	if m != nil {
		return m.Httpuuid
	}
	return ""
}

func (m *RespGetRooms) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RespGetRooms) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespGetRooms) GetData() *ResBox {
	if m != nil {
		return m.Data
	}
	return nil
}

//创建房间
type ReqCreateRoom struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateRoom) Reset()         { *m = ReqCreateRoom{} }
func (m *ReqCreateRoom) String() string { return proto.CompactTextString(m) }
func (*ReqCreateRoom) ProtoMessage()    {}
func (*ReqCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{18}
}

func (m *ReqCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateRoom.Unmarshal(m, b)
}
func (m *ReqCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateRoom.Marshal(b, m, deterministic)
}
func (m *ReqCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateRoom.Merge(m, src)
}
func (m *ReqCreateRoom) XXX_Size() int {
	return xxx_messageInfo_ReqCreateRoom.Size(m)
}
func (m *ReqCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateRoom proto.InternalMessageInfo

func (m *ReqCreateRoom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreateRoom) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type RespCreateRoom struct {
	Httpuuid             string   `protobuf:"bytes,1,opt,name=httpuuid,proto3" json:"httpuuid,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *ResBox  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateRoom) Reset()         { *m = RespCreateRoom{} }
func (m *RespCreateRoom) String() string { return proto.CompactTextString(m) }
func (*RespCreateRoom) ProtoMessage()    {}
func (*RespCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{19}
}

func (m *RespCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateRoom.Unmarshal(m, b)
}
func (m *RespCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateRoom.Marshal(b, m, deterministic)
}
func (m *RespCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateRoom.Merge(m, src)
}
func (m *RespCreateRoom) XXX_Size() int {
	return xxx_messageInfo_RespCreateRoom.Size(m)
}
func (m *RespCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateRoom proto.InternalMessageInfo

func (m *RespCreateRoom) GetHttpuuid() string {
	if m != nil {
		return m.Httpuuid
	}
	return ""
}

func (m *RespCreateRoom) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RespCreateRoom) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespCreateRoom) GetData() *ResBox {
	if m != nil {
		return m.Data
	}
	return nil
}

//加入房间
type ReqJoinRoom struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqJoinRoom) Reset()         { *m = ReqJoinRoom{} }
func (m *ReqJoinRoom) String() string { return proto.CompactTextString(m) }
func (*ReqJoinRoom) ProtoMessage()    {}
func (*ReqJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{20}
}

func (m *ReqJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqJoinRoom.Unmarshal(m, b)
}
func (m *ReqJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqJoinRoom.Marshal(b, m, deterministic)
}
func (m *ReqJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqJoinRoom.Merge(m, src)
}
func (m *ReqJoinRoom) XXX_Size() int {
	return xxx_messageInfo_ReqJoinRoom.Size(m)
}
func (m *ReqJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqJoinRoom proto.InternalMessageInfo

func (m *ReqJoinRoom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqJoinRoom) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type RespJoinRoom struct {
	Httpuuid             string   `protobuf:"bytes,1,opt,name=httpuuid,proto3" json:"httpuuid,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *ResBox  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespJoinRoom) Reset()         { *m = RespJoinRoom{} }
func (m *RespJoinRoom) String() string { return proto.CompactTextString(m) }
func (*RespJoinRoom) ProtoMessage()    {}
func (*RespJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{21}
}

func (m *RespJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespJoinRoom.Unmarshal(m, b)
}
func (m *RespJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespJoinRoom.Marshal(b, m, deterministic)
}
func (m *RespJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespJoinRoom.Merge(m, src)
}
func (m *RespJoinRoom) XXX_Size() int {
	return xxx_messageInfo_RespJoinRoom.Size(m)
}
func (m *RespJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_RespJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_RespJoinRoom proto.InternalMessageInfo

func (m *RespJoinRoom) GetHttpuuid() string {
	if m != nil {
		return m.Httpuuid
	}
	return ""
}

func (m *RespJoinRoom) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RespJoinRoom) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespJoinRoom) GetData() *ResBox {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Hero)(nil), "proto.Hero")
	proto.RegisterType((*Item)(nil), "proto.Item")
	proto.RegisterType((*Equip)(nil), "proto.Equip")
	proto.RegisterType((*AddHeroData)(nil), "proto.AddHeroData")
	proto.RegisterType((*AddItemData)(nil), "proto.AddItemData")
	proto.RegisterType((*AddEquipData)(nil), "proto.AddEquipData")
	proto.RegisterType((*OptionData)(nil), "proto.OptionData")
	proto.RegisterType((*OptionHeroEquip)(nil), "proto.OptionHeroEquip")
	proto.RegisterMapType((map[string]*OptionData)(nil), "proto.OptionHeroEquip.ListEntry")
	proto.RegisterType((*ResHero)(nil), "proto.resHero")
	proto.RegisterMapType((map[string]*Hero)(nil), "proto.resHero.HeroEntry")
	proto.RegisterType((*HeroReply)(nil), "proto.HeroReply")
	proto.RegisterType((*ResItem)(nil), "proto.resItem")
	proto.RegisterType((*ItemReply)(nil), "proto.ItemReply")
	proto.RegisterType((*ResEquip)(nil), "proto.resEquip")
	proto.RegisterMapType((map[string]*Equip)(nil), "proto.resEquip.EquipsEntry")
	proto.RegisterType((*EquipReply)(nil), "proto.EquipReply")
	proto.RegisterType((*ResBox)(nil), "proto.resBox")
	proto.RegisterType((*OpenBoxReply)(nil), "proto.OpenBoxReply")
	proto.RegisterType((*ReqGetRooms)(nil), "proto.reqGetRooms")
	proto.RegisterType((*RespGetRooms)(nil), "proto.respGetRooms")
	proto.RegisterType((*ReqCreateRoom)(nil), "proto.reqCreateRoom")
	proto.RegisterType((*RespCreateRoom)(nil), "proto.respCreateRoom")
	proto.RegisterType((*ReqJoinRoom)(nil), "proto.reqJoinRoom")
	proto.RegisterType((*RespJoinRoom)(nil), "proto.respJoinRoom")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 832 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x4f, 0x1b, 0x39,
	0x10, 0xcf, 0xc7, 0xe6, 0x6b, 0x02, 0x01, 0x0c, 0x87, 0xa2, 0x9c, 0x4e, 0x0a, 0xbe, 0x07, 0x78,
	0x40, 0x39, 0x1d, 0x1f, 0xd2, 0x09, 0x38, 0xe9, 0xc8, 0x81, 0x72, 0xe4, 0xaa, 0x22, 0xad, 0x78,
	0xea, 0xdb, 0x92, 0xb5, 0xda, 0x55, 0x93, 0xf5, 0xe2, 0xf5, 0x96, 0xe4, 0xa1, 0xef, 0xfd, 0xa7,
	0xaa, 0xfe, 0x6b, 0xd5, 0xd8, 0x5e, 0xef, 0x2e, 0x0a, 0x55, 0xa9, 0x28, 0x2f, 0x89, 0x67, 0xbc,
	0xbf, 0x99, 0xdf, 0x6f, 0x66, 0x6c, 0x43, 0x3b, 0x12, 0x5c, 0xf2, 0x81, 0xfa, 0x25, 0x35, 0xf5,
	0x47, 0x5f, 0x83, 0xf3, 0x1f, 0x13, 0x9c, 0x10, 0x70, 0x92, 0x24, 0xf0, 0xbb, 0xe5, 0x7e, 0x79,
	0xaf, 0xe5, 0xaa, 0x35, 0xe9, 0x41, 0xf3, 0x1d, 0x13, 0xfc, 0x66, 0x11, 0xb1, 0x6e, 0xa5, 0x5f,
	0xde, 0xab, 0xb9, 0xd6, 0x26, 0xdb, 0x50, 0x67, 0x77, 0x49, 0x10, 0xc5, 0xdd, 0x6a, 0xbf, 0xba,
	0xd7, 0x72, 0x8d, 0x45, 0xff, 0x01, 0xe7, 0x4a, 0xb2, 0x19, 0xe9, 0x40, 0xc5, 0x44, 0xab, 0xb9,
	0x95, 0xc0, 0x27, 0x5b, 0x50, 0x9b, 0xf0, 0x24, 0x94, 0x26, 0x90, 0x36, 0x30, 0xab, 0xc4, 0xe8,
	0x55, 0xe5, 0x54, 0x6b, 0xfa, 0x3f, 0xd4, 0x2e, 0x31, 0xd6, 0x52, 0x4a, 0xdb, 0x50, 0x0f, 0x24,
	0x9b, 0x5d, 0xf9, 0x26, 0x8e, 0xb1, 0xd0, 0x8f, 0xd4, 0xae, 0x7c, 0x15, 0xaa, 0xe5, 0x1a, 0x8b,
	0xfe, 0x0d, 0xed, 0x73, 0xdf, 0x47, 0x85, 0x17, 0x9e, 0xf4, 0xbe, 0x43, 0x65, 0x35, 0xaf, 0x92,
	0x8e, 0x15, 0x1c, 0x05, 0x3d, 0x0a, 0xdf, 0x85, 0x26, 0x72, 0x78, 0x15, 0xc4, 0x52, 0xc1, 0xdb,
	0x07, 0x6d, 0x5d, 0xe1, 0x01, 0xc2, 0x5c, 0xbb, 0x49, 0xcf, 0x60, 0xe5, 0xdc, 0xf7, 0x95, 0xb4,
	0x47, 0x83, 0x75, 0xa1, 0xa1, 0x05, 0xcd, 0x0d, 0x95, 0xd4, 0xa4, 0x67, 0x00, 0xd7, 0x91, 0x0c,
	0x78, 0x98, 0x62, 0x23, 0x4f, 0x48, 0x53, 0x5f, 0xb5, 0x46, 0x1d, 0x5c, 0x04, 0x6f, 0x83, 0xd0,
	0x9b, 0xaa, 0xe2, 0xb4, 0x5c, 0x6b, 0xd3, 0x2f, 0x65, 0x58, 0xd3, 0x70, 0x2c, 0xc5, 0x37, 0xcb,
	0x6b, 0xca, 0x58, 0xc9, 0x97, 0x91, 0x1c, 0x81, 0x33, 0x45, 0x81, 0x55, 0x25, 0xb0, 0x6f, 0x04,
	0x3e, 0x88, 0x38, 0x40, 0x99, 0x97, 0xa1, 0x14, 0x0b, 0x57, 0x7d, 0xdd, 0x1b, 0x43, 0xcb, 0xba,
	0xc8, 0x3a, 0x54, 0xdf, 0xb3, 0x85, 0xc9, 0x86, 0x4b, 0xb2, 0x0b, 0xb5, 0x0f, 0xde, 0x34, 0xd1,
	0xb3, 0xd5, 0x3e, 0xd8, 0x28, 0x44, 0x45, 0x99, 0xae, 0xde, 0x3f, 0xa9, 0xfc, 0x55, 0xa6, 0x1f,
	0xa1, 0x21, 0x58, 0xac, 0x46, 0x75, 0x1f, 0x1c, 0xa4, 0xd5, 0x2d, 0x2b, 0x32, 0x5d, 0x03, 0x33,
	0xbb, 0x03, 0x45, 0x47, 0x93, 0xc0, 0xaf, 0x7a, 0x17, 0xd0, 0xb2, 0xae, 0x25, 0x24, 0x76, 0x8a,
	0x24, 0xd2, 0xde, 0x21, 0x24, 0x9f, 0x3e, 0xd6, 0x51, 0x5c, 0x16, 0x4d, 0x17, 0x6a, 0x62, 0xa4,
	0x8c, 0x72, 0xd5, 0xb3, 0xb6, 0xad, 0x6a, 0x25, 0x57, 0x55, 0x02, 0xce, 0x84, 0xfb, 0x76, 0xca,
	0x71, 0x4d, 0x28, 0x38, 0xbe, 0x27, 0xbd, 0xae, 0xa3, 0xd2, 0x76, 0x8a, 0x22, 0x5c, 0xb5, 0x47,
	0xf7, 0x95, 0x66, 0x75, 0x9c, 0x76, 0xa0, 0x86, 0x93, 0x10, 0x1b, 0xd1, 0x85, 0x11, 0xd3, 0x3b,
	0x48, 0x51, 0x99, 0x3f, 0x9f, 0xa2, 0x4a, 0xa3, 0x29, 0x7e, 0x2a, 0x43, 0x53, 0xb0, 0x58, 0x4f,
	0xd4, 0xa1, 0xbd, 0x13, 0x34, 0xcb, 0x5f, 0x33, 0x88, 0x1e, 0x10, 0xf5, 0x1b, 0xeb, 0xee, 0x98,
	0x4f, 0x7b, 0x23, 0x68, 0xe7, 0xdc, 0x4b, 0x3a, 0x44, 0x8b, 0x1d, 0x5a, 0x31, 0x41, 0x15, 0x28,
	0xdf, 0xa2, 0x04, 0x40, 0xfb, 0x9e, 0xad, 0x00, 0xbf, 0x17, 0x0a, 0xb0, 0xf6, 0x40, 0x8d, 0xa9,
	0xc0, 0x18, 0xea, 0x82, 0xc5, 0x43, 0x3e, 0x27, 0xbf, 0x41, 0xf5, 0x96, 0xcf, 0x97, 0x75, 0x08,
	0xfd, 0x59, 0x0b, 0x2b, 0x8f, 0xb6, 0x30, 0x81, 0x95, 0xeb, 0x88, 0x85, 0x43, 0x3e, 0x7f, 0x3e,
	0x11, 0x3b, 0x05, 0x11, 0xab, 0x99, 0x08, 0xcc, 0xa2, 0x25, 0x1c, 0x43, 0x5b, 0xb0, 0xbb, 0x11,
	0x93, 0x2e, 0xe7, 0xb3, 0x18, 0xaf, 0xea, 0x58, 0x66, 0xb7, 0x8b, 0x36, 0xb0, 0x31, 0x53, 0x16,
	0x9a, 0x6b, 0x17, 0x97, 0xc8, 0x56, 0xb0, 0x38, 0xb2, 0xb8, 0x17, 0x63, 0xbb, 0x2a, 0xd8, 0xdd,
	0xbf, 0x82, 0x79, 0x92, 0x61, 0x62, 0x8c, 0x13, 0x7a, 0x33, 0x96, 0x5e, 0x64, 0xb8, 0x46, 0xb6,
	0xd1, 0x7d, 0x9a, 0x0e, 0x97, 0xf4, 0x1e, 0x3a, 0xc8, 0x36, 0x87, 0x7b, 0x21, 0xbe, 0x87, 0xaa,
	0xba, 0x63, 0x1e, 0x84, 0x4f, 0x60, 0x6b, 0x6a, 0x6b, 0x51, 0x2f, 0xc3, 0xf5, 0xe0, 0xb3, 0x03,
	0x8d, 0x91, 0x60, 0x4c, 0x32, 0x41, 0xfe, 0x84, 0x86, 0x79, 0x3a, 0x09, 0x31, 0xdf, 0xe6, 0x9e,
	0xd2, 0xde, 0x7a, 0xfe, 0xa6, 0xc4, 0x69, 0xa5, 0x25, 0x03, 0x51, 0x17, 0x56, 0x0e, 0x92, 0x3e,
	0x9f, 0x16, 0x62, 0xaf, 0x29, 0x5a, 0x22, 0x47, 0xd0, 0x4c, 0x5f, 0x45, 0xb2, 0x99, 0x61, 0xec,
	0x33, 0xd9, 0xdb, 0x28, 0x9c, 0x77, 0x83, 0x3a, 0x85, 0xd5, 0x61, 0x10, 0xfa, 0xd9, 0x63, 0xb6,
	0xbd, 0xfc, 0x49, 0x5a, 0xca, 0xf2, 0x0c, 0x3a, 0x37, 0x3e, 0xbf, 0x0f, 0x7f, 0x0c, 0x7d, 0x02,
	0xeb, 0x23, 0x26, 0x47, 0x9c, 0xfb, 0xf1, 0x70, 0xe1, 0x32, 0x3f, 0x99, 0xb0, 0x27, 0x88, 0x6d,
	0x98, 0xf3, 0xbd, 0x14, 0xb2, 0x69, 0x69, 0x64, 0x77, 0x00, 0x2d, 0x91, 0x63, 0x68, 0xda, 0x33,
	0x46, 0x6c, 0xd7, 0xec, 0x79, 0xb5, 0xb0, 0xfc, 0x61, 0x54, 0x35, 0x82, 0xdc, 0xb0, 0x6f, 0x65,
	0xc0, 0xcc, 0xdb, 0xfb, 0x25, 0x07, 0xcd, 0xdc, 0x3a, 0x67, 0x36, 0xb1, 0x19, 0x34, 0xf5, 0x15,
	0x72, 0xa6, 0x4e, 0x5a, 0x1a, 0x36, 0xdf, 0xd4, 0x07, 0x7f, 0x9c, 0x8a, 0x68, 0x72, 0x5b, 0x57,
	0xfb, 0x87, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x90, 0x1c, 0xed, 0x0d, 0x74, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	AddHero(ctx context.Context, in *AddHeroData, opts ...grpc.CallOption) (*HeroReply, error)
	AddItem(ctx context.Context, in *AddItemData, opts ...grpc.CallOption) (*ItemReply, error)
	AddEquip(ctx context.Context, in *AddEquipData, opts ...grpc.CallOption) (*EquipReply, error)
	BindHeroEquip(ctx context.Context, in *OptionHeroEquip, opts ...grpc.CallOption) (*HeroReply, error)
	TdownHeroEquip(ctx context.Context, in *OptionHeroEquip, opts ...grpc.CallOption) (*HeroReply, error)
	GetGoodsByReduce(ctx context.Context, in *AddItemData, opts ...grpc.CallOption) (*ItemReply, error)
	OpenBox(ctx context.Context, in *AddItemData, opts ...grpc.CallOption) (*OpenBoxReply, error)
	GetRooms(ctx context.Context, in *ReqGetRooms, opts ...grpc.CallOption) (*RespGetRooms, error)
	CreateRoom(ctx context.Context, in *ReqCreateRoom, opts ...grpc.CallOption) (*RespCreateRoom, error)
	JoinRoom(ctx context.Context, in *ReqJoinRoom, opts ...grpc.CallOption) (*RespJoinRoom, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) AddHero(ctx context.Context, in *AddHeroData, opts ...grpc.CallOption) (*HeroReply, error) {
	out := new(HeroReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/AddHero", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) AddItem(ctx context.Context, in *AddItemData, opts ...grpc.CallOption) (*ItemReply, error) {
	out := new(ItemReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) AddEquip(ctx context.Context, in *AddEquipData, opts ...grpc.CallOption) (*EquipReply, error) {
	out := new(EquipReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/AddEquip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) BindHeroEquip(ctx context.Context, in *OptionHeroEquip, opts ...grpc.CallOption) (*HeroReply, error) {
	out := new(HeroReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/BindHeroEquip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) TdownHeroEquip(ctx context.Context, in *OptionHeroEquip, opts ...grpc.CallOption) (*HeroReply, error) {
	out := new(HeroReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/TdownHeroEquip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetGoodsByReduce(ctx context.Context, in *AddItemData, opts ...grpc.CallOption) (*ItemReply, error) {
	out := new(ItemReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/GetGoodsByReduce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) OpenBox(ctx context.Context, in *AddItemData, opts ...grpc.CallOption) (*OpenBoxReply, error) {
	out := new(OpenBoxReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/OpenBox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetRooms(ctx context.Context, in *ReqGetRooms, opts ...grpc.CallOption) (*RespGetRooms, error) {
	out := new(RespGetRooms)
	err := c.cc.Invoke(ctx, "/proto.Greeter/GetRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateRoom(ctx context.Context, in *ReqCreateRoom, opts ...grpc.CallOption) (*RespCreateRoom, error) {
	out := new(RespCreateRoom)
	err := c.cc.Invoke(ctx, "/proto.Greeter/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) JoinRoom(ctx context.Context, in *ReqJoinRoom, opts ...grpc.CallOption) (*RespJoinRoom, error) {
	out := new(RespJoinRoom)
	err := c.cc.Invoke(ctx, "/proto.Greeter/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	AddHero(context.Context, *AddHeroData) (*HeroReply, error)
	AddItem(context.Context, *AddItemData) (*ItemReply, error)
	AddEquip(context.Context, *AddEquipData) (*EquipReply, error)
	BindHeroEquip(context.Context, *OptionHeroEquip) (*HeroReply, error)
	TdownHeroEquip(context.Context, *OptionHeroEquip) (*HeroReply, error)
	GetGoodsByReduce(context.Context, *AddItemData) (*ItemReply, error)
	OpenBox(context.Context, *AddItemData) (*OpenBoxReply, error)
	GetRooms(context.Context, *ReqGetRooms) (*RespGetRooms, error)
	CreateRoom(context.Context, *ReqCreateRoom) (*RespCreateRoom, error)
	JoinRoom(context.Context, *ReqJoinRoom) (*RespJoinRoom, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) AddHero(ctx context.Context, req *AddHeroData) (*HeroReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHero not implemented")
}
func (*UnimplementedGreeterServer) AddItem(ctx context.Context, req *AddItemData) (*ItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (*UnimplementedGreeterServer) AddEquip(ctx context.Context, req *AddEquipData) (*EquipReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEquip not implemented")
}
func (*UnimplementedGreeterServer) BindHeroEquip(ctx context.Context, req *OptionHeroEquip) (*HeroReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindHeroEquip not implemented")
}
func (*UnimplementedGreeterServer) TdownHeroEquip(ctx context.Context, req *OptionHeroEquip) (*HeroReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TdownHeroEquip not implemented")
}
func (*UnimplementedGreeterServer) GetGoodsByReduce(ctx context.Context, req *AddItemData) (*ItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsByReduce not implemented")
}
func (*UnimplementedGreeterServer) OpenBox(ctx context.Context, req *AddItemData) (*OpenBoxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenBox not implemented")
}
func (*UnimplementedGreeterServer) GetRooms(ctx context.Context, req *ReqGetRooms) (*RespGetRooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRooms not implemented")
}
func (*UnimplementedGreeterServer) CreateRoom(ctx context.Context, req *ReqCreateRoom) (*RespCreateRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedGreeterServer) JoinRoom(ctx context.Context, req *ReqJoinRoom) (*RespJoinRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_AddHero_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHeroData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AddHero(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/AddHero",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AddHero(ctx, req.(*AddHeroData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AddItem(ctx, req.(*AddItemData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_AddEquip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEquipData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AddEquip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/AddEquip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AddEquip(ctx, req.(*AddEquipData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_BindHeroEquip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionHeroEquip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).BindHeroEquip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/BindHeroEquip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).BindHeroEquip(ctx, req.(*OptionHeroEquip))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_TdownHeroEquip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionHeroEquip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).TdownHeroEquip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/TdownHeroEquip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).TdownHeroEquip(ctx, req.(*OptionHeroEquip))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetGoodsByReduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetGoodsByReduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/GetGoodsByReduce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetGoodsByReduce(ctx, req.(*AddItemData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_OpenBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).OpenBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/OpenBox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).OpenBox(ctx, req.(*AddItemData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetRooms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/GetRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetRooms(ctx, req.(*ReqGetRooms))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateRoom(ctx, req.(*ReqCreateRoom))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqJoinRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).JoinRoom(ctx, req.(*ReqJoinRoom))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddHero",
			Handler:    _Greeter_AddHero_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _Greeter_AddItem_Handler,
		},
		{
			MethodName: "AddEquip",
			Handler:    _Greeter_AddEquip_Handler,
		},
		{
			MethodName: "BindHeroEquip",
			Handler:    _Greeter_BindHeroEquip_Handler,
		},
		{
			MethodName: "TdownHeroEquip",
			Handler:    _Greeter_TdownHeroEquip_Handler,
		},
		{
			MethodName: "GetGoodsByReduce",
			Handler:    _Greeter_GetGoodsByReduce_Handler,
		},
		{
			MethodName: "OpenBox",
			Handler:    _Greeter_OpenBox_Handler,
		},
		{
			MethodName: "GetRooms",
			Handler:    _Greeter_GetRooms_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _Greeter_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _Greeter_JoinRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
