// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package smessage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerInfo struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServerInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ServerInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServerInfo) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// 请求服务器连接验证
type ReqServerVerify struct {
	Info                 *ServerInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqServerVerify) Reset()         { *m = ReqServerVerify{} }
func (m *ReqServerVerify) String() string { return proto.CompactTextString(m) }
func (*ReqServerVerify) ProtoMessage()    {}
func (*ReqServerVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ReqServerVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqServerVerify.Unmarshal(m, b)
}
func (m *ReqServerVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqServerVerify.Marshal(b, m, deterministic)
}
func (m *ReqServerVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqServerVerify.Merge(m, src)
}
func (m *ReqServerVerify) XXX_Size() int {
	return xxx_messageInfo_ReqServerVerify.Size(m)
}
func (m *ReqServerVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqServerVerify.DiscardUnknown(m)
}

var xxx_messageInfo_ReqServerVerify proto.InternalMessageInfo

func (m *ReqServerVerify) GetInfo() *ServerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 返回服务器验证信息
type RetServerVerify struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetServerVerify) Reset()         { *m = RetServerVerify{} }
func (m *RetServerVerify) String() string { return proto.CompactTextString(m) }
func (*RetServerVerify) ProtoMessage()    {}
func (*RetServerVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *RetServerVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetServerVerify.Unmarshal(m, b)
}
func (m *RetServerVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetServerVerify.Marshal(b, m, deterministic)
}
func (m *RetServerVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetServerVerify.Merge(m, src)
}
func (m *RetServerVerify) XXX_Size() int {
	return xxx_messageInfo_RetServerVerify.Size(m)
}
func (m *RetServerVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_RetServerVerify.DiscardUnknown(m)
}

var xxx_messageInfo_RetServerVerify proto.InternalMessageInfo

type OnlineUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineUserRequest) Reset()         { *m = OnlineUserRequest{} }
func (m *OnlineUserRequest) String() string { return proto.CompactTextString(m) }
func (*OnlineUserRequest) ProtoMessage()    {}
func (*OnlineUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *OnlineUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineUserRequest.Unmarshal(m, b)
}
func (m *OnlineUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineUserRequest.Marshal(b, m, deterministic)
}
func (m *OnlineUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineUserRequest.Merge(m, src)
}
func (m *OnlineUserRequest) XXX_Size() int {
	return xxx_messageInfo_OnlineUserRequest.Size(m)
}
func (m *OnlineUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineUserRequest proto.InternalMessageInfo

type OnlineUserResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineUserResponse) Reset()         { *m = OnlineUserResponse{} }
func (m *OnlineUserResponse) String() string { return proto.CompactTextString(m) }
func (*OnlineUserResponse) ProtoMessage()    {}
func (*OnlineUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *OnlineUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineUserResponse.Unmarshal(m, b)
}
func (m *OnlineUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineUserResponse.Marshal(b, m, deterministic)
}
func (m *OnlineUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineUserResponse.Merge(m, src)
}
func (m *OnlineUserResponse) XXX_Size() int {
	return xxx_messageInfo_OnlineUserResponse.Size(m)
}
func (m *OnlineUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineUserResponse proto.InternalMessageInfo

func (m *OnlineUserResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ServerIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerIdRequest) Reset()         { *m = ServerIdRequest{} }
func (m *ServerIdRequest) String() string { return proto.CompactTextString(m) }
func (*ServerIdRequest) ProtoMessage()    {}
func (*ServerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *ServerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerIdRequest.Unmarshal(m, b)
}
func (m *ServerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerIdRequest.Marshal(b, m, deterministic)
}
func (m *ServerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerIdRequest.Merge(m, src)
}
func (m *ServerIdRequest) XXX_Size() int {
	return xxx_messageInfo_ServerIdRequest.Size(m)
}
func (m *ServerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerIdRequest proto.InternalMessageInfo

type ServerIdResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerIdResponse) Reset()         { *m = ServerIdResponse{} }
func (m *ServerIdResponse) String() string { return proto.CompactTextString(m) }
func (*ServerIdResponse) ProtoMessage()    {}
func (*ServerIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *ServerIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerIdResponse.Unmarshal(m, b)
}
func (m *ServerIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerIdResponse.Marshal(b, m, deterministic)
}
func (m *ServerIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerIdResponse.Merge(m, src)
}
func (m *ServerIdResponse) XXX_Size() int {
	return xxx_messageInfo_ServerIdResponse.Size(m)
}
func (m *ServerIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerIdResponse proto.InternalMessageInfo

func (m *ServerIdResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerInfo)(nil), "smessage.ServerInfo")
	proto.RegisterType((*ReqServerVerify)(nil), "smessage.ReqServerVerify")
	proto.RegisterType((*RetServerVerify)(nil), "smessage.RetServerVerify")
	proto.RegisterType((*OnlineUserRequest)(nil), "smessage.OnlineUserRequest")
	proto.RegisterType((*OnlineUserResponse)(nil), "smessage.OnlineUserResponse")
	proto.RegisterType((*ServerIdRequest)(nil), "smessage.ServerIdRequest")
	proto.RegisterType((*ServerIdResponse)(nil), "smessage.ServerIdResponse")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0xdf, 0xb8, 0x7d, 0xf9, 0x73, 0xa1, 0x85, 0x1e, 0x1d, 0x42, 0x60, 0xa8, 0x3c, 0x45,
	0x0c, 0x41, 0x2a, 0x63, 0x37, 0x90, 0x40, 0x99, 0x00, 0x53, 0x18, 0xd8, 0x00, 0x5f, 0x51, 0x24,
	0x88, 0x13, 0xdb, 0x45, 0xea, 0xf7, 0xe1, 0x83, 0x22, 0x3b, 0x09, 0xa9, 0xd4, 0x6e, 0x97, 0xbb,
	0xe7, 0x79, 0x7e, 0x97, 0x33, 0x1c, 0x18, 0xd2, 0xdf, 0xa4, 0xd3, 0x52, 0x2b, 0xab, 0x70, 0xcf,
	0x7c, 0x91, 0x31, 0xaf, 0x1f, 0xc4, 0xe7, 0x00, 0x8f, 0x7e, 0x92, 0x15, 0x0b, 0x85, 0x43, 0x60,
	0x99, 0x8c, 0x82, 0x49, 0x90, 0x0c, 0x04, 0xcb, 0x24, 0x22, 0xf4, 0xe7, 0xab, 0x92, 0x22, 0xe6,
	0x3b, 0xbe, 0xf6, 0x9a, 0x32, 0xea, 0x4d, 0x82, 0x64, 0x5f, 0xb0, 0xac, 0x74, 0x9a, 0x7b, 0xa5,
	0x6d, 0xd4, 0xaf, 0x35, 0xae, 0xe6, 0x33, 0x38, 0x14, 0x54, 0xd5, 0xc1, 0xcf, 0xa4, 0xf3, 0xc5,
	0x0a, 0x13, 0xe8, 0x3b, 0x84, 0x0f, 0x0f, 0xa7, 0xe3, 0xb4, 0xdd, 0x20, 0xed, 0xf0, 0xc2, 0x2b,
	0xf8, 0xc8, 0x99, 0xed, 0xba, 0x99, 0x1f, 0xc3, 0xe8, 0xae, 0xf8, 0xcc, 0x0b, 0x7a, 0x32, 0xa4,
	0x05, 0x55, 0x4b, 0x32, 0x96, 0x9f, 0x03, 0xae, 0x37, 0x4d, 0xa9, 0x0a, 0x43, 0x38, 0x86, 0xff,
	0xef, 0x6a, 0x59, 0x58, 0x0f, 0xea, 0x89, 0xfa, 0xc3, 0x65, 0x36, 0x1c, 0xd9, 0xda, 0x39, 0x1c,
	0x75, 0xad, 0xc6, 0x3c, 0x04, 0x96, 0xcb, 0xc6, 0xc9, 0x72, 0x39, 0xfd, 0x09, 0x60, 0xf7, 0x56,
	0x13, 0x59, 0xd2, 0xf8, 0x00, 0x28, 0xa8, 0xea, 0x88, 0xd7, 0x2e, 0x18, 0x4f, 0xbb, 0x1f, 0xd9,
	0xd8, 0x30, 0x3e, 0xdb, 0x3e, 0xac, 0x61, 0xfc, 0x1f, 0xde, 0x40, 0xf8, 0x77, 0xa6, 0x4c, 0xe2,
	0xc9, 0xc6, 0x51, 0xda, 0x65, 0xe3, 0x78, 0xdb, 0xa8, 0xcd, 0xb9, 0x1a, 0xbc, 0x84, 0xe9, 0xc5,
	0xac, 0x55, 0xbc, 0xed, 0xf8, 0x47, 0xbe, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x38, 0x34, 0xcd,
	0xa6, 0xf4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	ReqOnlineUserCount(ctx context.Context, in *OnlineUserRequest, opts ...grpc.CallOption) (*OnlineUserResponse, error)
	ReqServerId(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerIdResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) ReqOnlineUserCount(ctx context.Context, in *OnlineUserRequest, opts ...grpc.CallOption) (*OnlineUserResponse, error) {
	out := new(OnlineUserResponse)
	err := c.cc.Invoke(ctx, "/smessage.Greeter/ReqOnlineUserCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ReqServerId(ctx context.Context, in *ServerIdRequest, opts ...grpc.CallOption) (*ServerIdResponse, error) {
	out := new(ServerIdResponse)
	err := c.cc.Invoke(ctx, "/smessage.Greeter/ReqServerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	ReqOnlineUserCount(context.Context, *OnlineUserRequest) (*OnlineUserResponse, error)
	ReqServerId(context.Context, *ServerIdRequest) (*ServerIdResponse, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) ReqOnlineUserCount(ctx context.Context, req *OnlineUserRequest) (*OnlineUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqOnlineUserCount not implemented")
}
func (*UnimplementedGreeterServer) ReqServerId(ctx context.Context, req *ServerIdRequest) (*ServerIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqServerId not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_ReqOnlineUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).ReqOnlineUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smessage.Greeter/ReqOnlineUserCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ReqOnlineUserCount(ctx, req.(*OnlineUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ReqServerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).ReqServerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smessage.Greeter/ReqServerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ReqServerId(ctx, req.(*ServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smessage.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqOnlineUserCount",
			Handler:    _Greeter_ReqOnlineUserCount_Handler,
		},
		{
			MethodName: "ReqServerId",
			Handler:    _Greeter_ReqServerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
