# accountdb
accountDB:
  ip: 192.168.1.72
  name: md_account
  user: root
  password: 123456
  maxIdleConns: 500
  maxOpenConns: 1000

# worldDB
worldDB:
  ip: 192.168.1.72
  name: md_actor
  user: root
  password: 123456
  maxIdleConns: 500
  maxOpenConns: 1000

#center
center:
  ip: 127.0.0.1
  port: 31500
  grpcport: 31599

#worlddbserver
worlddbserver:
  ip: 127.0.0.1
  port: 31400



# 服务器端口配置
account:
  ip: 192.168.1.72
  port: 31200

world:
  ip: 192.168.1.72
  port: 31300
#zoneserver
zone:
  ip: 127.0.0.1
  port: 31600

#grpcserver
grpcserver:
  ip: 127.0.0.1
  port: 31800

netgate:
  ip: 0.0.0.0
  port: 31700

# 服发现
etcd:
  endpoints:
    - http://192.168.1.72:2379

# uuid
snowflake:
  endpoints:
    - http://192.168.1.72:2379

raft:
  endpoints:
    - http://192.168.1.72:2381
# nats
nats:
  endpoints: 192.168.1.72:4222

# redis配置
redis:
  prefix: hero
  open: true
  ip: 192.168.1.72
  password: 123456
  port: 6379
  db: 0

#login
login:
  ip: 127.0.0.1
  port: 8081
#多个游戏服
mworld:
  endpoints:
    - 127.0.0.1:31300
    - 127.0.0.1:31301
#多网关服务器地址
mnetgate:
  endpoints:
    - 127.0.0.1:3000
    - 127.0.0.1:3001
    - 127.0.0.1:3002
mnetgateweb:
  websocket:
    - 127.0.0.1:3100
    - 127.0.0.1:3101
    - 127.0.0.1:3102
#多服务的账号服务器地址
maccount:
  endpoints:
    - 127.0.0.1:31200
    - 127.0.0.1:31201
# pvpweb服的接口地址
pvpweb:
  endpoints:
    - http://192.168.1.72:3002