// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package cmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登录
type C_G_LoginResquest struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Key                  int64    `protobuf:"varint,2,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_G_LoginResquest) Reset()         { *m = C_G_LoginResquest{} }
func (m *C_G_LoginResquest) String() string { return proto.CompactTextString(m) }
func (*C_G_LoginResquest) ProtoMessage()    {}
func (*C_G_LoginResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *C_G_LoginResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_G_LoginResquest.Unmarshal(m, b)
}
func (m *C_G_LoginResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_G_LoginResquest.Marshal(b, m, deterministic)
}
func (m *C_G_LoginResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_G_LoginResquest.Merge(m, src)
}
func (m *C_G_LoginResquest) XXX_Size() int {
	return xxx_messageInfo_C_G_LoginResquest.Size(m)
}
func (m *C_G_LoginResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_C_G_LoginResquest.DiscardUnknown(m)
}

var xxx_messageInfo_C_G_LoginResquest proto.InternalMessageInfo

func (m *C_G_LoginResquest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_G_LoginResquest) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

//登录
type G_C_LoginResponse struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Key                  int64    `protobuf:"varint,2,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G_C_LoginResponse) Reset()         { *m = G_C_LoginResponse{} }
func (m *G_C_LoginResponse) String() string { return proto.CompactTextString(m) }
func (*G_C_LoginResponse) ProtoMessage()    {}
func (*G_C_LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *G_C_LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G_C_LoginResponse.Unmarshal(m, b)
}
func (m *G_C_LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G_C_LoginResponse.Marshal(b, m, deterministic)
}
func (m *G_C_LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G_C_LoginResponse.Merge(m, src)
}
func (m *G_C_LoginResponse) XXX_Size() int {
	return xxx_messageInfo_G_C_LoginResponse.Size(m)
}
func (m *G_C_LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_G_C_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_G_C_LoginResponse proto.InternalMessageInfo

func (m *G_C_LoginResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *G_C_LoginResponse) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

//登录
type C_A_LoginRequest struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	AccountName          string   `protobuf:"bytes,2,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	BuildNo              string   `protobuf:"bytes,5,opt,name=BuildNo,proto3" json:"BuildNo,omitempty"`
	Key                  int64    `protobuf:"varint,6,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_A_LoginRequest) Reset()         { *m = C_A_LoginRequest{} }
func (m *C_A_LoginRequest) String() string { return proto.CompactTextString(m) }
func (*C_A_LoginRequest) ProtoMessage()    {}
func (*C_A_LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *C_A_LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_A_LoginRequest.Unmarshal(m, b)
}
func (m *C_A_LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_A_LoginRequest.Marshal(b, m, deterministic)
}
func (m *C_A_LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_A_LoginRequest.Merge(m, src)
}
func (m *C_A_LoginRequest) XXX_Size() int {
	return xxx_messageInfo_C_A_LoginRequest.Size(m)
}
func (m *C_A_LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C_A_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C_A_LoginRequest proto.InternalMessageInfo

func (m *C_A_LoginRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_LoginRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *C_A_LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *C_A_LoginRequest) GetBuildNo() string {
	if m != nil {
		return m.BuildNo
	}
	return ""
}

func (m *C_A_LoginRequest) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

//登录反馈
type A_C_LoginResponse struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	AccountName          string   `protobuf:"bytes,4,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *A_C_LoginResponse) Reset()         { *m = A_C_LoginResponse{} }
func (m *A_C_LoginResponse) String() string { return proto.CompactTextString(m) }
func (*A_C_LoginResponse) ProtoMessage()    {}
func (*A_C_LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *A_C_LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_A_C_LoginResponse.Unmarshal(m, b)
}
func (m *A_C_LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_A_C_LoginResponse.Marshal(b, m, deterministic)
}
func (m *A_C_LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_A_C_LoginResponse.Merge(m, src)
}
func (m *A_C_LoginResponse) XXX_Size() int {
	return xxx_messageInfo_A_C_LoginResponse.Size(m)
}
func (m *A_C_LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_A_C_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_A_C_LoginResponse proto.InternalMessageInfo

func (m *A_C_LoginResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *A_C_LoginResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *A_C_LoginResponse) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

//注册
type C_A_RegisterRequest struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	AccountName          string   `protobuf:"bytes,2,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_A_RegisterRequest) Reset()         { *m = C_A_RegisterRequest{} }
func (m *C_A_RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*C_A_RegisterRequest) ProtoMessage()    {}
func (*C_A_RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *C_A_RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_A_RegisterRequest.Unmarshal(m, b)
}
func (m *C_A_RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_A_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *C_A_RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_A_RegisterRequest.Merge(m, src)
}
func (m *C_A_RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_C_A_RegisterRequest.Size(m)
}
func (m *C_A_RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C_A_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C_A_RegisterRequest proto.InternalMessageInfo

func (m *C_A_RegisterRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_RegisterRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *C_A_RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//注册反馈
type A_C_RegisterResponse struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *A_C_RegisterResponse) Reset()         { *m = A_C_RegisterResponse{} }
func (m *A_C_RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*A_C_RegisterResponse) ProtoMessage()    {}
func (*A_C_RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{5}
}

func (m *A_C_RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_A_C_RegisterResponse.Unmarshal(m, b)
}
func (m *A_C_RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_A_C_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *A_C_RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_A_C_RegisterResponse.Merge(m, src)
}
func (m *A_C_RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_A_C_RegisterResponse.Size(m)
}
func (m *A_C_RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_A_C_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_A_C_RegisterResponse proto.InternalMessageInfo

func (m *A_C_RegisterResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *A_C_RegisterResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

//创角
type C_W_CreatePlayerRequest struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=Sex,proto3" json:"Sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_W_CreatePlayerRequest) Reset()         { *m = C_W_CreatePlayerRequest{} }
func (m *C_W_CreatePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*C_W_CreatePlayerRequest) ProtoMessage()    {}
func (*C_W_CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{6}
}

func (m *C_W_CreatePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_W_CreatePlayerRequest.Unmarshal(m, b)
}
func (m *C_W_CreatePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_W_CreatePlayerRequest.Marshal(b, m, deterministic)
}
func (m *C_W_CreatePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_W_CreatePlayerRequest.Merge(m, src)
}
func (m *C_W_CreatePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_C_W_CreatePlayerRequest.Size(m)
}
func (m *C_W_CreatePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C_W_CreatePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C_W_CreatePlayerRequest proto.InternalMessageInfo

func (m *C_W_CreatePlayerRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_CreatePlayerRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *C_W_CreatePlayerRequest) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

//创角反馈
type W_C_CreatePlayerResponse struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	PlayerId             int64    `protobuf:"varint,3,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *W_C_CreatePlayerResponse) Reset()         { *m = W_C_CreatePlayerResponse{} }
func (m *W_C_CreatePlayerResponse) String() string { return proto.CompactTextString(m) }
func (*W_C_CreatePlayerResponse) ProtoMessage()    {}
func (*W_C_CreatePlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{7}
}

func (m *W_C_CreatePlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W_C_CreatePlayerResponse.Unmarshal(m, b)
}
func (m *W_C_CreatePlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W_C_CreatePlayerResponse.Marshal(b, m, deterministic)
}
func (m *W_C_CreatePlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W_C_CreatePlayerResponse.Merge(m, src)
}
func (m *W_C_CreatePlayerResponse) XXX_Size() int {
	return xxx_messageInfo_W_C_CreatePlayerResponse.Size(m)
}
func (m *W_C_CreatePlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_W_C_CreatePlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_W_C_CreatePlayerResponse proto.InternalMessageInfo

func (m *W_C_CreatePlayerResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_CreatePlayerResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *W_C_CreatePlayerResponse) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

//登录游戏
type C_W_Game_LoginRequset struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	PlayerId             int64    `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_W_Game_LoginRequset) Reset()         { *m = C_W_Game_LoginRequset{} }
func (m *C_W_Game_LoginRequset) String() string { return proto.CompactTextString(m) }
func (*C_W_Game_LoginRequset) ProtoMessage()    {}
func (*C_W_Game_LoginRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{8}
}

func (m *C_W_Game_LoginRequset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_W_Game_LoginRequset.Unmarshal(m, b)
}
func (m *C_W_Game_LoginRequset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_W_Game_LoginRequset.Marshal(b, m, deterministic)
}
func (m *C_W_Game_LoginRequset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_W_Game_LoginRequset.Merge(m, src)
}
func (m *C_W_Game_LoginRequset) XXX_Size() int {
	return xxx_messageInfo_C_W_Game_LoginRequset.Size(m)
}
func (m *C_W_Game_LoginRequset) XXX_DiscardUnknown() {
	xxx_messageInfo_C_W_Game_LoginRequset.DiscardUnknown(m)
}

var xxx_messageInfo_C_W_Game_LoginRequset proto.InternalMessageInfo

func (m *C_W_Game_LoginRequset) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_Game_LoginRequset) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

//选角反馈
type W_C_SelectPlayerResponse struct {
	PacketHead           *Ipacket      `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	AccountId            int64         `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	PlayerData           []*PlayerData `protobuf:"bytes,3,rep,name=PlayerData,proto3" json:"PlayerData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *W_C_SelectPlayerResponse) Reset()         { *m = W_C_SelectPlayerResponse{} }
func (m *W_C_SelectPlayerResponse) String() string { return proto.CompactTextString(m) }
func (*W_C_SelectPlayerResponse) ProtoMessage()    {}
func (*W_C_SelectPlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{9}
}

func (m *W_C_SelectPlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W_C_SelectPlayerResponse.Unmarshal(m, b)
}
func (m *W_C_SelectPlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W_C_SelectPlayerResponse.Marshal(b, m, deterministic)
}
func (m *W_C_SelectPlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W_C_SelectPlayerResponse.Merge(m, src)
}
func (m *W_C_SelectPlayerResponse) XXX_Size() int {
	return xxx_messageInfo_W_C_SelectPlayerResponse.Size(m)
}
func (m *W_C_SelectPlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_W_C_SelectPlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_W_C_SelectPlayerResponse proto.InternalMessageInfo

func (m *W_C_SelectPlayerResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_SelectPlayerResponse) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *W_C_SelectPlayerResponse) GetPlayerData() []*PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

type C_G_LogoutResponse struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_G_LogoutResponse) Reset()         { *m = C_G_LogoutResponse{} }
func (m *C_G_LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*C_G_LogoutResponse) ProtoMessage()    {}
func (*C_G_LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{10}
}

func (m *C_G_LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_G_LogoutResponse.Unmarshal(m, b)
}
func (m *C_G_LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_G_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *C_G_LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_G_LogoutResponse.Merge(m, src)
}
func (m *C_G_LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_C_G_LogoutResponse.Size(m)
}
func (m *C_G_LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_C_G_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_C_G_LogoutResponse proto.InternalMessageInfo

func (m *C_G_LogoutResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

//聊天
type C_W_ChatMessage struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Sender               int64    `protobuf:"varint,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Recver               int64    `protobuf:"varint,3,opt,name=Recver,proto3" json:"Recver,omitempty"`
	MessageType          int32    `protobuf:"varint,4,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_W_ChatMessage) Reset()         { *m = C_W_ChatMessage{} }
func (m *C_W_ChatMessage) String() string { return proto.CompactTextString(m) }
func (*C_W_ChatMessage) ProtoMessage()    {}
func (*C_W_ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{11}
}

func (m *C_W_ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_W_ChatMessage.Unmarshal(m, b)
}
func (m *C_W_ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_W_ChatMessage.Marshal(b, m, deterministic)
}
func (m *C_W_ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_W_ChatMessage.Merge(m, src)
}
func (m *C_W_ChatMessage) XXX_Size() int {
	return xxx_messageInfo_C_W_ChatMessage.Size(m)
}
func (m *C_W_ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_C_W_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_C_W_ChatMessage proto.InternalMessageInfo

func (m *C_W_ChatMessage) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_ChatMessage) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *C_W_ChatMessage) GetRecver() int64 {
	if m != nil {
		return m.Recver
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type W_C_ChatMessage struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Sender               int64    `protobuf:"varint,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	SenderName           string   `protobuf:"bytes,3,opt,name=SenderName,proto3" json:"SenderName,omitempty"`
	Recver               int64    `protobuf:"varint,4,opt,name=Recver,proto3" json:"Recver,omitempty"`
	RecverName           string   `protobuf:"bytes,5,opt,name=RecverName,proto3" json:"RecverName,omitempty"`
	MessageType          int32    `protobuf:"varint,6,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Message              string   `protobuf:"bytes,7,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *W_C_ChatMessage) Reset()         { *m = W_C_ChatMessage{} }
func (m *W_C_ChatMessage) String() string { return proto.CompactTextString(m) }
func (*W_C_ChatMessage) ProtoMessage()    {}
func (*W_C_ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{12}
}

func (m *W_C_ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W_C_ChatMessage.Unmarshal(m, b)
}
func (m *W_C_ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W_C_ChatMessage.Marshal(b, m, deterministic)
}
func (m *W_C_ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W_C_ChatMessage.Merge(m, src)
}
func (m *W_C_ChatMessage) XXX_Size() int {
	return xxx_messageInfo_W_C_ChatMessage.Size(m)
}
func (m *W_C_ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_W_C_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_W_C_ChatMessage proto.InternalMessageInfo

func (m *W_C_ChatMessage) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_ChatMessage) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *W_C_ChatMessage) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *W_C_ChatMessage) GetRecver() int64 {
	if m != nil {
		return m.Recver
	}
	return 0
}

func (m *W_C_ChatMessage) GetRecverName() string {
	if m != nil {
		return m.RecverName
	}
	return ""
}

func (m *W_C_ChatMessage) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *W_C_ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type W_C_Test struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	PlayerId             int64    `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Recv                 []int32  `protobuf:"varint,3,rep,packed,name=Recv,proto3" json:"Recv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *W_C_Test) Reset()         { *m = W_C_Test{} }
func (m *W_C_Test) String() string { return proto.CompactTextString(m) }
func (*W_C_Test) ProtoMessage()    {}
func (*W_C_Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{13}
}

func (m *W_C_Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W_C_Test.Unmarshal(m, b)
}
func (m *W_C_Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W_C_Test.Marshal(b, m, deterministic)
}
func (m *W_C_Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W_C_Test.Merge(m, src)
}
func (m *W_C_Test) XXX_Size() int {
	return xxx_messageInfo_W_C_Test.Size(m)
}
func (m *W_C_Test) XXX_DiscardUnknown() {
	xxx_messageInfo_W_C_Test.DiscardUnknown(m)
}

var xxx_messageInfo_W_C_Test proto.InternalMessageInfo

func (m *W_C_Test) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_Test) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *W_C_Test) GetRecv() []int32 {
	if m != nil {
		return m.Recv
	}
	return nil
}

func init() {
	proto.RegisterType((*C_G_LoginResquest)(nil), "cmessage.C_G_LoginResquest")
	proto.RegisterType((*G_C_LoginResponse)(nil), "cmessage.G_C_LoginResponse")
	proto.RegisterType((*C_A_LoginRequest)(nil), "cmessage.C_A_LoginRequest")
	proto.RegisterType((*A_C_LoginResponse)(nil), "cmessage.A_C_LoginResponse")
	proto.RegisterType((*C_A_RegisterRequest)(nil), "cmessage.C_A_RegisterRequest")
	proto.RegisterType((*A_C_RegisterResponse)(nil), "cmessage.A_C_RegisterResponse")
	proto.RegisterType((*C_W_CreatePlayerRequest)(nil), "cmessage.C_W_CreatePlayerRequest")
	proto.RegisterType((*W_C_CreatePlayerResponse)(nil), "cmessage.W_C_CreatePlayerResponse")
	proto.RegisterType((*C_W_Game_LoginRequset)(nil), "cmessage.C_W_Game_LoginRequset")
	proto.RegisterType((*W_C_SelectPlayerResponse)(nil), "cmessage.W_C_SelectPlayerResponse")
	proto.RegisterType((*C_G_LogoutResponse)(nil), "cmessage.C_G_LogoutResponse")
	proto.RegisterType((*C_W_ChatMessage)(nil), "cmessage.C_W_ChatMessage")
	proto.RegisterType((*W_C_ChatMessage)(nil), "cmessage.W_C_ChatMessage")
	proto.RegisterType((*W_C_Test)(nil), "cmessage.W_C_Test")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xeb, 0x38, 0x4d, 0x26, 0xa0, 0x36, 0x26, 0x80, 0x55, 0xa1, 0x28, 0xf2, 0x29, 0xa7,
	0x20, 0x0a, 0x37, 0x4e, 0xa9, 0x41, 0xa1, 0x02, 0xaa, 0x68, 0x53, 0xa9, 0x88, 0x8b, 0xb5, 0x75,
	0x86, 0x10, 0x91, 0xc4, 0x66, 0x77, 0x0d, 0xe4, 0x52, 0x6e, 0xbc, 0x07, 0x4f, 0x00, 0x8f, 0xc6,
	0x23, 0xa0, 0xfd, 0x71, 0xbc, 0x0d, 0x52, 0x0f, 0x49, 0x50, 0x6f, 0x33, 0xb3, 0xeb, 0x99, 0xef,
	0xfb, 0x66, 0x66, 0x0d, 0x77, 0x92, 0xd9, 0x14, 0x17, 0xa2, 0x97, 0xb1, 0x54, 0xa4, 0x7e, 0x2d,
	0x99, 0x23, 0xe7, 0x74, 0x82, 0x47, 0xf5, 0x2c, 0xbf, 0xd4, 0xc1, 0xf0, 0x1d, 0x34, 0xa3, 0x78,
	0x10, 0xbf, 0x49, 0x27, 0xd3, 0x05, 0x41, 0xfe, 0x39, 0x47, 0x2e, 0xfc, 0x27, 0x00, 0x43, 0x9a,
	0x7c, 0x42, 0xf1, 0x0a, 0xe9, 0x38, 0x70, 0x3a, 0x4e, 0xb7, 0x71, 0xdc, 0xec, 0x15, 0x9f, 0xf7,
	0x4e, 0x33, 0x75, 0x48, 0xac, 0x4b, 0xfe, 0x21, 0xb8, 0xaf, 0x71, 0x19, 0xec, 0x75, 0x9c, 0xae,
	0x4b, 0xa4, 0x29, 0x33, 0x0f, 0xe2, 0x68, 0x95, 0x39, 0x4b, 0x17, 0x1c, 0x77, 0x93, 0xf9, 0x97,
	0x03, 0x87, 0x51, 0xdc, 0x2f, 0x52, 0x6f, 0x8c, 0xb9, 0x03, 0x8d, 0x7e, 0x92, 0xa4, 0xf9, 0x42,
	0x9c, 0xd1, 0x39, 0xaa, 0x0a, 0x75, 0x62, 0x87, 0xfc, 0x23, 0xa8, 0x0d, 0x29, 0xe7, 0x5f, 0x53,
	0x36, 0x0e, 0x5c, 0x75, 0xbc, 0xf2, 0xfd, 0x00, 0xf6, 0x4f, 0xf2, 0xe9, 0x6c, 0x7c, 0x96, 0x06,
	0x9e, 0x3a, 0x2a, 0xdc, 0x02, 0x71, 0xb5, 0x44, 0x7c, 0x05, 0xcd, 0xfe, 0x2e, 0xb4, 0x68, 0x81,
	0xf7, 0x92, 0xb1, 0x94, 0x29, 0xac, 0x1e, 0xd1, 0xce, 0x3a, 0x8f, 0xca, 0x3f, 0x3c, 0xc2, 0x1f,
	0x0e, 0xdc, 0x93, 0x8a, 0x11, 0x9c, 0x4c, 0xb9, 0x40, 0x76, 0x5b, 0xa2, 0x85, 0x31, 0xb4, 0xa4,
	0x10, 0x25, 0x8e, 0x1d, 0x6b, 0x11, 0x5e, 0xc1, 0xc3, 0x28, 0xbe, 0x88, 0x23, 0x86, 0x54, 0xe0,
	0x70, 0x46, 0x97, 0x5b, 0x91, 0x6d, 0x03, 0xe8, 0x1c, 0x16, 0x57, 0x2b, 0x22, 0x3b, 0x3d, 0xc2,
	0x6f, 0x8a, 0xa5, 0x47, 0xa4, 0x19, 0x7e, 0x87, 0xe0, 0x22, 0x8e, 0xd6, 0xea, 0xef, 0xba, 0xe1,
	0x52, 0x61, 0x95, 0xfa, 0x54, 0x2b, 0xec, 0x92, 0x95, 0x1f, 0x7e, 0x80, 0xfb, 0x52, 0x80, 0x01,
	0x9d, 0x63, 0xb9, 0x20, 0x1c, 0x37, 0xa2, 0x6f, 0xd7, 0xd9, 0x5b, 0xab, 0xf3, 0xd3, 0xd1, 0x4c,
	0x47, 0x38, 0xc3, 0x44, 0x6c, 0xcf, 0xf4, 0x11, 0xd4, 0xcd, 0x10, 0xad, 0x8a, 0x95, 0x01, 0xff,
	0x59, 0xd1, 0x88, 0x17, 0x54, 0xd0, 0xc0, 0xed, 0xb8, 0xdd, 0xc6, 0x71, 0xab, 0x4c, 0x58, 0x9e,
	0x11, 0xeb, 0x5e, 0x38, 0x00, 0xdf, 0x3c, 0x6e, 0x69, 0x2e, 0xb6, 0x00, 0x17, 0xfe, 0x76, 0xe0,
	0x40, 0x8d, 0xd5, 0x47, 0x2a, 0xde, 0xea, 0x7b, 0x9b, 0x70, 0x7c, 0x00, 0xd5, 0x11, 0x2e, 0xc6,
	0xc8, 0x0c, 0x41, 0xe3, 0xc9, 0x38, 0xc1, 0xe4, 0x0b, 0x32, 0xd3, 0x4d, 0xe3, 0xc9, 0x5d, 0x33,
	0xd5, 0xce, 0x97, 0x99, 0x5e, 0x6c, 0x8f, 0xd8, 0x21, 0xf9, 0x08, 0x19, 0xb7, 0x78, 0x84, 0x8c,
	0x1b, 0xfe, 0x71, 0xe0, 0x40, 0x4d, 0xe2, 0xff, 0x81, 0xdc, 0x06, 0xd0, 0x96, 0xda, 0x0c, 0xbd,
	0xe6, 0x56, 0xc4, 0xa2, 0x54, 0xb9, 0x46, 0xa9, 0x0d, 0xa0, 0x2d, 0xf5, 0x9d, 0xc6, 0x6c, 0x45,
	0xd6, 0x29, 0x57, 0x6f, 0xa4, 0xbc, 0x7f, 0x9d, 0xf2, 0x1c, 0x6a, 0x92, 0xf1, 0xf9, 0x86, 0xcb,
	0x7e, 0xc3, 0xb4, 0xfb, 0x3e, 0x54, 0x24, 0x48, 0x35, 0x79, 0x1e, 0x51, 0xf6, 0xc9, 0xdd, 0xf7,
	0x8d, 0xde, 0xe3, 0xe7, 0x45, 0xca, 0xcb, 0xaa, 0xfa, 0xa1, 0x3e, 0xfd, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0x70, 0x62, 0xc2, 0x75, 0x07, 0x00, 0x00,
}
