// Code generated by protoc-gen-go. DO NOT EDIT.
// source: global.proto

package cmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 初始化玩家
// 游戏开始
// 游戏结束
// 时间
type GameTimeReq struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameTimeReq) Reset()         { *m = GameTimeReq{} }
func (m *GameTimeReq) String() string { return proto.CompactTextString(m) }
func (*GameTimeReq) ProtoMessage()    {}
func (*GameTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{0}
}

func (m *GameTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTimeReq.Unmarshal(m, b)
}
func (m *GameTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTimeReq.Marshal(b, m, deterministic)
}
func (m *GameTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTimeReq.Merge(m, src)
}
func (m *GameTimeReq) XXX_Size() int {
	return xxx_messageInfo_GameTimeReq.Size(m)
}
func (m *GameTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GameTimeReq proto.InternalMessageInfo

func (m *GameTimeReq) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

type GameTimeResp struct {
	PacketHead *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	//返回服务器时间，long 类型时间戳
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameTimeResp) Reset()         { *m = GameTimeResp{} }
func (m *GameTimeResp) String() string { return proto.CompactTextString(m) }
func (*GameTimeResp) ProtoMessage()    {}
func (*GameTimeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{1}
}

func (m *GameTimeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTimeResp.Unmarshal(m, b)
}
func (m *GameTimeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTimeResp.Marshal(b, m, deterministic)
}
func (m *GameTimeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTimeResp.Merge(m, src)
}
func (m *GameTimeResp) XXX_Size() int {
	return xxx_messageInfo_GameTimeResp.Size(m)
}
func (m *GameTimeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTimeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GameTimeResp proto.InternalMessageInfo

func (m *GameTimeResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *GameTimeResp) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*GameTimeReq)(nil), "cmessage.GameTimeReq")
	proto.RegisterType((*GameTimeResp)(nil), "cmessage.GameTimeResp")
}

func init() { proto.RegisterFile("global.proto", fileDescriptor_4baa8fc7dedf329e) }

var fileDescriptor_4baa8fc7dedf329e = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0xc9, 0x4f,
	0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xce, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x95, 0xe2, 0x2c, 0x28, 0x4d, 0x82, 0x08, 0x2a, 0x39, 0x70, 0x71, 0xbb, 0x27, 0xe6,
	0xa6, 0x86, 0x64, 0xe6, 0xa6, 0x06, 0xa5, 0x16, 0x0a, 0x19, 0x72, 0x71, 0x05, 0x24, 0x26, 0x67,
	0xa7, 0x96, 0x78, 0xa4, 0x26, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x09, 0xea, 0xc1,
	0x34, 0xea, 0x79, 0x16, 0x80, 0x25, 0x83, 0x90, 0x14, 0x29, 0x85, 0x72, 0xf1, 0x20, 0x4c, 0x28,
	0x2e, 0x20, 0xc3, 0x08, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xcc, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xe6, 0x20, 0x30, 0xdb, 0x89, 0x37, 0x8a, 0x5b, 0x4f, 0xdf, 0x1a, 0xa6, 0x2d, 0x89, 0x0d,
	0xec, 0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x1d, 0x8a, 0x7a, 0xd3, 0x00, 0x00,
	0x00,
}
