// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package cmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//新版本的协议
//登录
//移动
type MovingReq struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Skill                int64    `protobuf:"varint,3,opt,name=skill,proto3" json:"skill,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	X                    float32  `protobuf:"fixed32,5,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	SkillId              int32    `protobuf:"varint,7,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Msg                  string   `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Dir                  float32  `protobuf:"fixed32,9,opt,name=dir,proto3" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovingReq) Reset()         { *m = MovingReq{} }
func (m *MovingReq) String() string { return proto.CompactTextString(m) }
func (*MovingReq) ProtoMessage()    {}
func (*MovingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *MovingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovingReq.Unmarshal(m, b)
}
func (m *MovingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovingReq.Marshal(b, m, deterministic)
}
func (m *MovingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovingReq.Merge(m, src)
}
func (m *MovingReq) XXX_Size() int {
	return xxx_messageInfo_MovingReq.Size(m)
}
func (m *MovingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MovingReq.DiscardUnknown(m)
}

var xxx_messageInfo_MovingReq proto.InternalMessageInfo

func (m *MovingReq) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *MovingReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MovingReq) GetSkill() int64 {
	if m != nil {
		return m.Skill
	}
	return 0
}

func (m *MovingReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MovingReq) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MovingReq) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MovingReq) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *MovingReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *MovingReq) GetDir() float32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

type MovingResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Speed                int32    `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	ReduceSpeedTs        int64    `protobuf:"varint,3,opt,name=reduceSpeedTs,proto3" json:"reduceSpeedTs,omitempty"`
	Direction            float32  `protobuf:"fixed32,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Barrier              int32    `protobuf:"varint,5,opt,name=barrier,proto3" json:"barrier,omitempty"`
	Dizzy                int32    `protobuf:"varint,6,opt,name=dizzy,proto3" json:"dizzy,omitempty"`
	DizzyTs              int32    `protobuf:"varint,7,opt,name=dizzyTs,proto3" json:"dizzyTs,omitempty"`
	X                    float32  `protobuf:"fixed32,8,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,9,opt,name=y,proto3" json:"y,omitempty"`
	StopMove             int32    `protobuf:"varint,10,opt,name=stopMove,proto3" json:"stopMove,omitempty"`
	StopMoveTs           int64    `protobuf:"varint,11,opt,name=stopMoveTs,proto3" json:"stopMoveTs,omitempty"`
	PosUpdateTs          int64    `protobuf:"varint,12,opt,name=posUpdateTs,proto3" json:"posUpdateTs,omitempty"`
	User                 string   `protobuf:"bytes,13,opt,name=user,proto3" json:"user,omitempty"`
	FuncName             string   `protobuf:"bytes,14,opt,name=funcName,proto3" json:"funcName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovingResp) Reset()         { *m = MovingResp{} }
func (m *MovingResp) String() string { return proto.CompactTextString(m) }
func (*MovingResp) ProtoMessage()    {}
func (*MovingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *MovingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovingResp.Unmarshal(m, b)
}
func (m *MovingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovingResp.Marshal(b, m, deterministic)
}
func (m *MovingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovingResp.Merge(m, src)
}
func (m *MovingResp) XXX_Size() int {
	return xxx_messageInfo_MovingResp.Size(m)
}
func (m *MovingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MovingResp.DiscardUnknown(m)
}

var xxx_messageInfo_MovingResp proto.InternalMessageInfo

func (m *MovingResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *MovingResp) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *MovingResp) GetReduceSpeedTs() int64 {
	if m != nil {
		return m.ReduceSpeedTs
	}
	return 0
}

func (m *MovingResp) GetDirection() float32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *MovingResp) GetBarrier() int32 {
	if m != nil {
		return m.Barrier
	}
	return 0
}

func (m *MovingResp) GetDizzy() int32 {
	if m != nil {
		return m.Dizzy
	}
	return 0
}

func (m *MovingResp) GetDizzyTs() int32 {
	if m != nil {
		return m.DizzyTs
	}
	return 0
}

func (m *MovingResp) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MovingResp) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MovingResp) GetStopMove() int32 {
	if m != nil {
		return m.StopMove
	}
	return 0
}

func (m *MovingResp) GetStopMoveTs() int64 {
	if m != nil {
		return m.StopMoveTs
	}
	return 0
}

func (m *MovingResp) GetPosUpdateTs() int64 {
	if m != nil {
		return m.PosUpdateTs
	}
	return 0
}

func (m *MovingResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *MovingResp) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

//离开
//加入
//攻击
type AttackReq struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Round                int32    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Skill                int32    `protobuf:"varint,5,opt,name=skill,proto3" json:"skill,omitempty"`
	SkillId              int32    `protobuf:"varint,6,opt,name=skillId,proto3" json:"skillId,omitempty"`
	X                    float32  `protobuf:"fixed32,7,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,8,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,9,opt,name=z,proto3" json:"z,omitempty"`
	Msg                  string   `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttackReq) Reset()         { *m = AttackReq{} }
func (m *AttackReq) String() string { return proto.CompactTextString(m) }
func (*AttackReq) ProtoMessage()    {}
func (*AttackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{2}
}

func (m *AttackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttackReq.Unmarshal(m, b)
}
func (m *AttackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttackReq.Marshal(b, m, deterministic)
}
func (m *AttackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttackReq.Merge(m, src)
}
func (m *AttackReq) XXX_Size() int {
	return xxx_messageInfo_AttackReq.Size(m)
}
func (m *AttackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AttackReq.DiscardUnknown(m)
}

var xxx_messageInfo_AttackReq proto.InternalMessageInfo

func (m *AttackReq) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *AttackReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *AttackReq) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *AttackReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *AttackReq) GetSkill() int32 {
	if m != nil {
		return m.Skill
	}
	return 0
}

func (m *AttackReq) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *AttackReq) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AttackReq) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *AttackReq) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *AttackReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AttackResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Skill                int32    `protobuf:"varint,4,opt,name=skill,proto3" json:"skill,omitempty"`
	SkillId              int32    `protobuf:"varint,5,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Shield               int32    `protobuf:"varint,6,opt,name=shield,proto3" json:"shield,omitempty"`
	IsSkip               int32    `protobuf:"varint,7,opt,name=isSkip,proto3" json:"isSkip,omitempty"`
	Hp                   int32    `protobuf:"varint,8,opt,name=hp,proto3" json:"hp,omitempty"`
	Damage               int32    `protobuf:"varint,9,opt,name=damage,proto3" json:"damage,omitempty"`
	Critical             int32    `protobuf:"varint,10,opt,name=critical,proto3" json:"critical,omitempty"`
	Ts                   int64    `protobuf:"varint,11,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttackResp) Reset()         { *m = AttackResp{} }
func (m *AttackResp) String() string { return proto.CompactTextString(m) }
func (*AttackResp) ProtoMessage()    {}
func (*AttackResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3}
}

func (m *AttackResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttackResp.Unmarshal(m, b)
}
func (m *AttackResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttackResp.Marshal(b, m, deterministic)
}
func (m *AttackResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttackResp.Merge(m, src)
}
func (m *AttackResp) XXX_Size() int {
	return xxx_messageInfo_AttackResp.Size(m)
}
func (m *AttackResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AttackResp.DiscardUnknown(m)
}

var xxx_messageInfo_AttackResp proto.InternalMessageInfo

func (m *AttackResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *AttackResp) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *AttackResp) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *AttackResp) GetSkill() int32 {
	if m != nil {
		return m.Skill
	}
	return 0
}

func (m *AttackResp) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *AttackResp) GetShield() int32 {
	if m != nil {
		return m.Shield
	}
	return 0
}

func (m *AttackResp) GetIsSkip() int32 {
	if m != nil {
		return m.IsSkip
	}
	return 0
}

func (m *AttackResp) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *AttackResp) GetDamage() int32 {
	if m != nil {
		return m.Damage
	}
	return 0
}

func (m *AttackResp) GetCritical() int32 {
	if m != nil {
		return m.Critical
	}
	return 0
}

func (m *AttackResp) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

//attack_cure
//attack_dizzy
//attack_reduce_speed
//攻击成功
type AttackSuccessResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Skill                int32    `protobuf:"varint,4,opt,name=skill,proto3" json:"skill,omitempty"`
	SkillId              int32    `protobuf:"varint,5,opt,name=skillId,proto3" json:"skillId,omitempty"`
	X                    float32  `protobuf:"fixed32,6,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,7,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,8,opt,name=z,proto3" json:"z,omitempty"`
	Msg                  string   `protobuf:"bytes,9,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttackSuccessResp) Reset()         { *m = AttackSuccessResp{} }
func (m *AttackSuccessResp) String() string { return proto.CompactTextString(m) }
func (*AttackSuccessResp) ProtoMessage()    {}
func (*AttackSuccessResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4}
}

func (m *AttackSuccessResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttackSuccessResp.Unmarshal(m, b)
}
func (m *AttackSuccessResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttackSuccessResp.Marshal(b, m, deterministic)
}
func (m *AttackSuccessResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttackSuccessResp.Merge(m, src)
}
func (m *AttackSuccessResp) XXX_Size() int {
	return xxx_messageInfo_AttackSuccessResp.Size(m)
}
func (m *AttackSuccessResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AttackSuccessResp.DiscardUnknown(m)
}

var xxx_messageInfo_AttackSuccessResp proto.InternalMessageInfo

func (m *AttackSuccessResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *AttackSuccessResp) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *AttackSuccessResp) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *AttackSuccessResp) GetSkill() int32 {
	if m != nil {
		return m.Skill
	}
	return 0
}

func (m *AttackSuccessResp) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *AttackSuccessResp) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AttackSuccessResp) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *AttackSuccessResp) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *AttackSuccessResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//跳跃
type JumpReq struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JumpReq) Reset()         { *m = JumpReq{} }
func (m *JumpReq) String() string { return proto.CompactTextString(m) }
func (*JumpReq) ProtoMessage()    {}
func (*JumpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{5}
}

func (m *JumpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JumpReq.Unmarshal(m, b)
}
func (m *JumpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JumpReq.Marshal(b, m, deterministic)
}
func (m *JumpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JumpReq.Merge(m, src)
}
func (m *JumpReq) XXX_Size() int {
	return xxx_messageInfo_JumpReq.Size(m)
}
func (m *JumpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JumpReq.DiscardUnknown(m)
}

var xxx_messageInfo_JumpReq proto.InternalMessageInfo

func (m *JumpReq) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *JumpReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type JumpResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JumpResp) Reset()         { *m = JumpResp{} }
func (m *JumpResp) String() string { return proto.CompactTextString(m) }
func (*JumpResp) ProtoMessage()    {}
func (*JumpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{6}
}

func (m *JumpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JumpResp.Unmarshal(m, b)
}
func (m *JumpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JumpResp.Marshal(b, m, deterministic)
}
func (m *JumpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JumpResp.Merge(m, src)
}
func (m *JumpResp) XXX_Size() int {
	return xxx_messageInfo_JumpResp.Size(m)
}
func (m *JumpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JumpResp.DiscardUnknown(m)
}

var xxx_messageInfo_JumpResp proto.InternalMessageInfo

func (m *JumpResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *JumpResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

//技能护盾
type SkillShieldResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Shield               int32    `protobuf:"varint,3,opt,name=shield,proto3" json:"shield,omitempty"`
	ShieldTs             int64    `protobuf:"varint,4,opt,name=shieldTs,proto3" json:"shieldTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillShieldResp) Reset()         { *m = SkillShieldResp{} }
func (m *SkillShieldResp) String() string { return proto.CompactTextString(m) }
func (*SkillShieldResp) ProtoMessage()    {}
func (*SkillShieldResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{7}
}

func (m *SkillShieldResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillShieldResp.Unmarshal(m, b)
}
func (m *SkillShieldResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillShieldResp.Marshal(b, m, deterministic)
}
func (m *SkillShieldResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillShieldResp.Merge(m, src)
}
func (m *SkillShieldResp) XXX_Size() int {
	return xxx_messageInfo_SkillShieldResp.Size(m)
}
func (m *SkillShieldResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillShieldResp.DiscardUnknown(m)
}

var xxx_messageInfo_SkillShieldResp proto.InternalMessageInfo

func (m *SkillShieldResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *SkillShieldResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SkillShieldResp) GetShield() int32 {
	if m != nil {
		return m.Shield
	}
	return 0
}

func (m *SkillShieldResp) GetShieldTs() int64 {
	if m != nil {
		return m.ShieldTs
	}
	return 0
}

//技能反伤
type SkillThornsResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Thorns               int32    `protobuf:"varint,3,opt,name=thorns,proto3" json:"thorns,omitempty"`
	ThornsTs             int64    `protobuf:"varint,4,opt,name=thornsTs,proto3" json:"thornsTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillThornsResp) Reset()         { *m = SkillThornsResp{} }
func (m *SkillThornsResp) String() string { return proto.CompactTextString(m) }
func (*SkillThornsResp) ProtoMessage()    {}
func (*SkillThornsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{8}
}

func (m *SkillThornsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillThornsResp.Unmarshal(m, b)
}
func (m *SkillThornsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillThornsResp.Marshal(b, m, deterministic)
}
func (m *SkillThornsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillThornsResp.Merge(m, src)
}
func (m *SkillThornsResp) XXX_Size() int {
	return xxx_messageInfo_SkillThornsResp.Size(m)
}
func (m *SkillThornsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillThornsResp.DiscardUnknown(m)
}

var xxx_messageInfo_SkillThornsResp proto.InternalMessageInfo

func (m *SkillThornsResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *SkillThornsResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SkillThornsResp) GetThorns() int32 {
	if m != nil {
		return m.Thorns
	}
	return 0
}

func (m *SkillThornsResp) GetThornsTs() int64 {
	if m != nil {
		return m.ThornsTs
	}
	return 0
}

//技能效果变身
type SkillDeformationResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	AddAtk               int32    `protobuf:"varint,3,opt,name=addAtk,proto3" json:"addAtk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillDeformationResp) Reset()         { *m = SkillDeformationResp{} }
func (m *SkillDeformationResp) String() string { return proto.CompactTextString(m) }
func (*SkillDeformationResp) ProtoMessage()    {}
func (*SkillDeformationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{9}
}

func (m *SkillDeformationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillDeformationResp.Unmarshal(m, b)
}
func (m *SkillDeformationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillDeformationResp.Marshal(b, m, deterministic)
}
func (m *SkillDeformationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillDeformationResp.Merge(m, src)
}
func (m *SkillDeformationResp) XXX_Size() int {
	return xxx_messageInfo_SkillDeformationResp.Size(m)
}
func (m *SkillDeformationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillDeformationResp.DiscardUnknown(m)
}

var xxx_messageInfo_SkillDeformationResp proto.InternalMessageInfo

func (m *SkillDeformationResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *SkillDeformationResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SkillDeformationResp) GetAddAtk() int32 {
	if m != nil {
		return m.AddAtk
	}
	return 0
}

//技能效果无敌
type SkillImmuneResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Immune               int32    `protobuf:"varint,3,opt,name=immune,proto3" json:"immune,omitempty"`
	ImmuneTs             int64    `protobuf:"varint,4,opt,name=immuneTs,proto3" json:"immuneTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillImmuneResp) Reset()         { *m = SkillImmuneResp{} }
func (m *SkillImmuneResp) String() string { return proto.CompactTextString(m) }
func (*SkillImmuneResp) ProtoMessage()    {}
func (*SkillImmuneResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{10}
}

func (m *SkillImmuneResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillImmuneResp.Unmarshal(m, b)
}
func (m *SkillImmuneResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillImmuneResp.Marshal(b, m, deterministic)
}
func (m *SkillImmuneResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillImmuneResp.Merge(m, src)
}
func (m *SkillImmuneResp) XXX_Size() int {
	return xxx_messageInfo_SkillImmuneResp.Size(m)
}
func (m *SkillImmuneResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillImmuneResp.DiscardUnknown(m)
}

var xxx_messageInfo_SkillImmuneResp proto.InternalMessageInfo

func (m *SkillImmuneResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *SkillImmuneResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SkillImmuneResp) GetImmune() int32 {
	if m != nil {
		return m.Immune
	}
	return 0
}

func (m *SkillImmuneResp) GetImmuneTs() int64 {
	if m != nil {
		return m.ImmuneTs
	}
	return 0
}

//skill_movig
//加入房间
//房间消息
//复活
type ReliveResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Round                int32    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Part                 int32    `protobuf:"varint,4,opt,name=part,proto3" json:"part,omitempty"`
	Hid                  string   `protobuf:"bytes,5,opt,name=hid,proto3" json:"hid,omitempty"`
	Type                 int32    `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	DefPercent           int32    `protobuf:"varint,7,opt,name=defPercent,proto3" json:"defPercent,omitempty"`
	Hp                   int64    `protobuf:"varint,8,opt,name=hp,proto3" json:"hp,omitempty"`
	UpdateTs             int64    `protobuf:"varint,9,opt,name=updateTs,proto3" json:"updateTs,omitempty"`
	X                    float32  `protobuf:"fixed32,10,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,11,opt,name=y,proto3" json:"y,omitempty"`
	Speed                int32    `protobuf:"varint,12,opt,name=speed,proto3" json:"speed,omitempty"`
	ReduceSpeedTs        int64    `protobuf:"varint,13,opt,name=reduceSpeedTs,proto3" json:"reduceSpeedTs,omitempty"`
	Direction            int32    `protobuf:"varint,14,opt,name=direction,proto3" json:"direction,omitempty"`
	Barrier              int32    `protobuf:"varint,15,opt,name=barrier,proto3" json:"barrier,omitempty"`
	Dizzy                int32    `protobuf:"varint,16,opt,name=dizzy,proto3" json:"dizzy,omitempty"`
	DizzyTs              int64    `protobuf:"varint,17,opt,name=dizzyTs,proto3" json:"dizzyTs,omitempty"`
	Shield               int32    `protobuf:"varint,18,opt,name=shield,proto3" json:"shield,omitempty"`
	ShieldTs             int64    `protobuf:"varint,19,opt,name=shieldTs,proto3" json:"shieldTs,omitempty"`
	Immune               int32    `protobuf:"varint,20,opt,name=immune,proto3" json:"immune,omitempty"`
	ImmuneTs             int64    `protobuf:"varint,21,opt,name=immuneTs,proto3" json:"immuneTs,omitempty"`
	Thorns               int32    `protobuf:"varint,22,opt,name=thorns,proto3" json:"thorns,omitempty"`
	ThornsTs             int64    `protobuf:"varint,23,opt,name=thornsTs,proto3" json:"thornsTs,omitempty"`
	StopMoveTs           int64    `protobuf:"varint,24,opt,name=stopMoveTs,proto3" json:"stopMoveTs,omitempty"`
	StopMove             int32    `protobuf:"varint,25,opt,name=stopMove,proto3" json:"stopMove,omitempty"`
	AddDef               int32    `protobuf:"varint,26,opt,name=addDef,proto3" json:"addDef,omitempty"`
	AddDefTs             int64    `protobuf:"varint,27,opt,name=addDefTs,proto3" json:"addDefTs,omitempty"`
	AddAtk               int32    `protobuf:"varint,28,opt,name=addAtk,proto3" json:"addAtk,omitempty"`
	PosUpdateTs          int64    `protobuf:"varint,29,opt,name=posUpdateTs,proto3" json:"posUpdateTs,omitempty"`
	DieTs                int64    `protobuf:"varint,30,opt,name=dieTs,proto3" json:"dieTs,omitempty"`
	AllAttr              int32    `protobuf:"varint,31,opt,name=allAttr,proto3" json:"allAttr,omitempty"`
	Dvt                  int32    `protobuf:"varint,32,opt,name=dvt,proto3" json:"dvt,omitempty"`
	GetDvt_              int32    `protobuf:"varint,33,opt,name=getDvt,proto3" json:"getDvt,omitempty"`
	DesDvt               int32    `protobuf:"varint,34,opt,name=desDvt,proto3" json:"desDvt,omitempty"`
	Kill                 int32    `protobuf:"varint,35,opt,name=kill,proto3" json:"kill,omitempty"`
	Die                  int32    `protobuf:"varint,36,opt,name=die,proto3" json:"die,omitempty"`
	Dps                  int32    `protobuf:"varint,37,opt,name=dps,proto3" json:"dps,omitempty"`
	Skill_1101Cd         int32    `protobuf:"varint,38,opt,name=skill_1101_cd,json=skill1101Cd,proto3" json:"skill_1101_cd,omitempty"`
	Skill_1102Cd         int32    `protobuf:"varint,39,opt,name=skill_1102_cd,json=skill1102Cd,proto3" json:"skill_1102_cd,omitempty"`
	Skill_1103Cd         int32    `protobuf:"varint,40,opt,name=skill_1103_cd,json=skill1103Cd,proto3" json:"skill_1103_cd,omitempty"`
	Skill_1104Cd         int32    `protobuf:"varint,41,opt,name=skill_1104_cd,json=skill1104Cd,proto3" json:"skill_1104_cd,omitempty"`
	Item_1002Cd          int32    `protobuf:"varint,42,opt,name=item_1002_cd,json=item1002Cd,proto3" json:"item_1002_cd,omitempty"`
	Item_1003Cd          int32    `protobuf:"varint,43,opt,name=item_1003_cd,json=item1003Cd,proto3" json:"item_1003_cd,omitempty"`
	Item_1004Cd          int32    `protobuf:"varint,44,opt,name=item_1004_cd,json=item1004Cd,proto3" json:"item_1004_cd,omitempty"`
	Equip_1              int32    `protobuf:"varint,45,opt,name=equip_1,json=equip1,proto3" json:"equip_1,omitempty"`
	Equip_3              int32    `protobuf:"varint,46,opt,name=equip_3,json=equip3,proto3" json:"equip_3,omitempty"`
	Equip                []int32  `protobuf:"varint,47,rep,packed,name=equip,proto3" json:"equip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReliveResp) Reset()         { *m = ReliveResp{} }
func (m *ReliveResp) String() string { return proto.CompactTextString(m) }
func (*ReliveResp) ProtoMessage()    {}
func (*ReliveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{11}
}

func (m *ReliveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReliveResp.Unmarshal(m, b)
}
func (m *ReliveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReliveResp.Marshal(b, m, deterministic)
}
func (m *ReliveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReliveResp.Merge(m, src)
}
func (m *ReliveResp) XXX_Size() int {
	return xxx_messageInfo_ReliveResp.Size(m)
}
func (m *ReliveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReliveResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReliveResp proto.InternalMessageInfo

func (m *ReliveResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *ReliveResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReliveResp) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ReliveResp) GetPart() int32 {
	if m != nil {
		return m.Part
	}
	return 0
}

func (m *ReliveResp) GetHid() string {
	if m != nil {
		return m.Hid
	}
	return ""
}

func (m *ReliveResp) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReliveResp) GetDefPercent() int32 {
	if m != nil {
		return m.DefPercent
	}
	return 0
}

func (m *ReliveResp) GetHp() int64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *ReliveResp) GetUpdateTs() int64 {
	if m != nil {
		return m.UpdateTs
	}
	return 0
}

func (m *ReliveResp) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ReliveResp) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ReliveResp) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *ReliveResp) GetReduceSpeedTs() int64 {
	if m != nil {
		return m.ReduceSpeedTs
	}
	return 0
}

func (m *ReliveResp) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *ReliveResp) GetBarrier() int32 {
	if m != nil {
		return m.Barrier
	}
	return 0
}

func (m *ReliveResp) GetDizzy() int32 {
	if m != nil {
		return m.Dizzy
	}
	return 0
}

func (m *ReliveResp) GetDizzyTs() int64 {
	if m != nil {
		return m.DizzyTs
	}
	return 0
}

func (m *ReliveResp) GetShield() int32 {
	if m != nil {
		return m.Shield
	}
	return 0
}

func (m *ReliveResp) GetShieldTs() int64 {
	if m != nil {
		return m.ShieldTs
	}
	return 0
}

func (m *ReliveResp) GetImmune() int32 {
	if m != nil {
		return m.Immune
	}
	return 0
}

func (m *ReliveResp) GetImmuneTs() int64 {
	if m != nil {
		return m.ImmuneTs
	}
	return 0
}

func (m *ReliveResp) GetThorns() int32 {
	if m != nil {
		return m.Thorns
	}
	return 0
}

func (m *ReliveResp) GetThornsTs() int64 {
	if m != nil {
		return m.ThornsTs
	}
	return 0
}

func (m *ReliveResp) GetStopMoveTs() int64 {
	if m != nil {
		return m.StopMoveTs
	}
	return 0
}

func (m *ReliveResp) GetStopMove() int32 {
	if m != nil {
		return m.StopMove
	}
	return 0
}

func (m *ReliveResp) GetAddDef() int32 {
	if m != nil {
		return m.AddDef
	}
	return 0
}

func (m *ReliveResp) GetAddDefTs() int64 {
	if m != nil {
		return m.AddDefTs
	}
	return 0
}

func (m *ReliveResp) GetAddAtk() int32 {
	if m != nil {
		return m.AddAtk
	}
	return 0
}

func (m *ReliveResp) GetPosUpdateTs() int64 {
	if m != nil {
		return m.PosUpdateTs
	}
	return 0
}

func (m *ReliveResp) GetDieTs() int64 {
	if m != nil {
		return m.DieTs
	}
	return 0
}

func (m *ReliveResp) GetAllAttr() int32 {
	if m != nil {
		return m.AllAttr
	}
	return 0
}

func (m *ReliveResp) GetDvt() int32 {
	if m != nil {
		return m.Dvt
	}
	return 0
}

func (m *ReliveResp) GetGetDvt_() int32 {
	if m != nil {
		return m.GetDvt_
	}
	return 0
}

func (m *ReliveResp) GetDesDvt() int32 {
	if m != nil {
		return m.DesDvt
	}
	return 0
}

func (m *ReliveResp) GetKill() int32 {
	if m != nil {
		return m.Kill
	}
	return 0
}

func (m *ReliveResp) GetDie() int32 {
	if m != nil {
		return m.Die
	}
	return 0
}

func (m *ReliveResp) GetDps() int32 {
	if m != nil {
		return m.Dps
	}
	return 0
}

func (m *ReliveResp) GetSkill_1101Cd() int32 {
	if m != nil {
		return m.Skill_1101Cd
	}
	return 0
}

func (m *ReliveResp) GetSkill_1102Cd() int32 {
	if m != nil {
		return m.Skill_1102Cd
	}
	return 0
}

func (m *ReliveResp) GetSkill_1103Cd() int32 {
	if m != nil {
		return m.Skill_1103Cd
	}
	return 0
}

func (m *ReliveResp) GetSkill_1104Cd() int32 {
	if m != nil {
		return m.Skill_1104Cd
	}
	return 0
}

func (m *ReliveResp) GetItem_1002Cd() int32 {
	if m != nil {
		return m.Item_1002Cd
	}
	return 0
}

func (m *ReliveResp) GetItem_1003Cd() int32 {
	if m != nil {
		return m.Item_1003Cd
	}
	return 0
}

func (m *ReliveResp) GetItem_1004Cd() int32 {
	if m != nil {
		return m.Item_1004Cd
	}
	return 0
}

func (m *ReliveResp) GetEquip_1() int32 {
	if m != nil {
		return m.Equip_1
	}
	return 0
}

func (m *ReliveResp) GetEquip_3() int32 {
	if m != nil {
		return m.Equip_3
	}
	return 0
}

func (m *ReliveResp) GetEquip() []int32 {
	if m != nil {
		return m.Equip
	}
	return nil
}

//夺旗
type FlagReq struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagReq) Reset()         { *m = FlagReq{} }
func (m *FlagReq) String() string { return proto.CompactTextString(m) }
func (*FlagReq) ProtoMessage()    {}
func (*FlagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{12}
}

func (m *FlagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagReq.Unmarshal(m, b)
}
func (m *FlagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagReq.Marshal(b, m, deterministic)
}
func (m *FlagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagReq.Merge(m, src)
}
func (m *FlagReq) XXX_Size() int {
	return xxx_messageInfo_FlagReq.Size(m)
}
func (m *FlagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagReq.DiscardUnknown(m)
}

var xxx_messageInfo_FlagReq proto.InternalMessageInfo

func (m *FlagReq) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

type FlagResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagResp) Reset()         { *m = FlagResp{} }
func (m *FlagResp) String() string { return proto.CompactTextString(m) }
func (*FlagResp) ProtoMessage()    {}
func (*FlagResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{13}
}

func (m *FlagResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagResp.Unmarshal(m, b)
}
func (m *FlagResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagResp.Marshal(b, m, deterministic)
}
func (m *FlagResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagResp.Merge(m, src)
}
func (m *FlagResp) XXX_Size() int {
	return xxx_messageInfo_FlagResp.Size(m)
}
func (m *FlagResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagResp.DiscardUnknown(m)
}

var xxx_messageInfo_FlagResp proto.InternalMessageInfo

func (m *FlagResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

//夺旗成功
type FlagSuccessResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Part                 int32    `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
	Part1Score           int32    `protobuf:"varint,3,opt,name=part1score,proto3" json:"part1score,omitempty"`
	Part2Score           int32    `protobuf:"varint,4,opt,name=part2score,proto3" json:"part2score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagSuccessResp) Reset()         { *m = FlagSuccessResp{} }
func (m *FlagSuccessResp) String() string { return proto.CompactTextString(m) }
func (*FlagSuccessResp) ProtoMessage()    {}
func (*FlagSuccessResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{14}
}

func (m *FlagSuccessResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagSuccessResp.Unmarshal(m, b)
}
func (m *FlagSuccessResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagSuccessResp.Marshal(b, m, deterministic)
}
func (m *FlagSuccessResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagSuccessResp.Merge(m, src)
}
func (m *FlagSuccessResp) XXX_Size() int {
	return xxx_messageInfo_FlagSuccessResp.Size(m)
}
func (m *FlagSuccessResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagSuccessResp.DiscardUnknown(m)
}

var xxx_messageInfo_FlagSuccessResp proto.InternalMessageInfo

func (m *FlagSuccessResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *FlagSuccessResp) GetPart() int32 {
	if m != nil {
		return m.Part
	}
	return 0
}

func (m *FlagSuccessResp) GetPart1Score() int32 {
	if m != nil {
		return m.Part1Score
	}
	return 0
}

func (m *FlagSuccessResp) GetPart2Score() int32 {
	if m != nil {
		return m.Part2Score
	}
	return 0
}

//使用道具
type UseItemReq struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	ItemId               int32    `protobuf:"varint,3,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Msg                  string   `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseItemReq) Reset()         { *m = UseItemReq{} }
func (m *UseItemReq) String() string { return proto.CompactTextString(m) }
func (*UseItemReq) ProtoMessage()    {}
func (*UseItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{15}
}

func (m *UseItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseItemReq.Unmarshal(m, b)
}
func (m *UseItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseItemReq.Marshal(b, m, deterministic)
}
func (m *UseItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseItemReq.Merge(m, src)
}
func (m *UseItemReq) XXX_Size() int {
	return xxx_messageInfo_UseItemReq.Size(m)
}
func (m *UseItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UseItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_UseItemReq proto.InternalMessageInfo

func (m *UseItemReq) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *UseItemReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *UseItemReq) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *UseItemReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UseItemReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//加血
type AddHpResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Hp                   int64    `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	Add                  int32    `protobuf:"varint,3,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddHpResp) Reset()         { *m = AddHpResp{} }
func (m *AddHpResp) String() string { return proto.CompactTextString(m) }
func (*AddHpResp) ProtoMessage()    {}
func (*AddHpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{16}
}

func (m *AddHpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHpResp.Unmarshal(m, b)
}
func (m *AddHpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHpResp.Marshal(b, m, deterministic)
}
func (m *AddHpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHpResp.Merge(m, src)
}
func (m *AddHpResp) XXX_Size() int {
	return xxx_messageInfo_AddHpResp.Size(m)
}
func (m *AddHpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHpResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddHpResp proto.InternalMessageInfo

func (m *AddHpResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *AddHpResp) GetHp() int64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *AddHpResp) GetAdd() int32 {
	if m != nil {
		return m.Add
	}
	return 0
}

//使用道具1003
type UseItem1003Resp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Hp                   int32    `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	AllAttr              int32    `protobuf:"varint,3,opt,name=allAttr,proto3" json:"allAttr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseItem1003Resp) Reset()         { *m = UseItem1003Resp{} }
func (m *UseItem1003Resp) String() string { return proto.CompactTextString(m) }
func (*UseItem1003Resp) ProtoMessage()    {}
func (*UseItem1003Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{17}
}

func (m *UseItem1003Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseItem1003Resp.Unmarshal(m, b)
}
func (m *UseItem1003Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseItem1003Resp.Marshal(b, m, deterministic)
}
func (m *UseItem1003Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseItem1003Resp.Merge(m, src)
}
func (m *UseItem1003Resp) XXX_Size() int {
	return xxx_messageInfo_UseItem1003Resp.Size(m)
}
func (m *UseItem1003Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_UseItem1003Resp.DiscardUnknown(m)
}

var xxx_messageInfo_UseItem1003Resp proto.InternalMessageInfo

func (m *UseItem1003Resp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *UseItem1003Resp) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *UseItem1003Resp) GetAllAttr() int32 {
	if m != nil {
		return m.AllAttr
	}
	return 0
}

//更新dvt
type UpdateDvtResp struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Get                  int32    `protobuf:"varint,4,opt,name=get,proto3" json:"get,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDvtResp) Reset()         { *m = UpdateDvtResp{} }
func (m *UpdateDvtResp) String() string { return proto.CompactTextString(m) }
func (*UpdateDvtResp) ProtoMessage()    {}
func (*UpdateDvtResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{18}
}

func (m *UpdateDvtResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDvtResp.Unmarshal(m, b)
}
func (m *UpdateDvtResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDvtResp.Marshal(b, m, deterministic)
}
func (m *UpdateDvtResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDvtResp.Merge(m, src)
}
func (m *UpdateDvtResp) XXX_Size() int {
	return xxx_messageInfo_UpdateDvtResp.Size(m)
}
func (m *UpdateDvtResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDvtResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDvtResp proto.InternalMessageInfo

func (m *UpdateDvtResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *UpdateDvtResp) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *UpdateDvtResp) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *UpdateDvtResp) GetGet() int32 {
	if m != nil {
		return m.Get
	}
	return 0
}

//排行榜
//奖励
type RewardReq struct {
	PacketHead           *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewardReq) Reset()         { *m = RewardReq{} }
func (m *RewardReq) String() string { return proto.CompactTextString(m) }
func (*RewardReq) ProtoMessage()    {}
func (*RewardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{19}
}

func (m *RewardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardReq.Unmarshal(m, b)
}
func (m *RewardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardReq.Marshal(b, m, deterministic)
}
func (m *RewardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardReq.Merge(m, src)
}
func (m *RewardReq) XXX_Size() int {
	return xxx_messageInfo_RewardReq.Size(m)
}
func (m *RewardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardReq.DiscardUnknown(m)
}

var xxx_messageInfo_RewardReq proto.InternalMessageInfo

func (m *RewardReq) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

type RewardItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewardItem) Reset()         { *m = RewardItem{} }
func (m *RewardItem) String() string { return proto.CompactTextString(m) }
func (*RewardItem) ProtoMessage()    {}
func (*RewardItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{20}
}

func (m *RewardItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardItem.Unmarshal(m, b)
}
func (m *RewardItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardItem.Marshal(b, m, deterministic)
}
func (m *RewardItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardItem.Merge(m, src)
}
func (m *RewardItem) XXX_Size() int {
	return xxx_messageInfo_RewardItem.Size(m)
}
func (m *RewardItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardItem.DiscardUnknown(m)
}

var xxx_messageInfo_RewardItem proto.InternalMessageInfo

func (m *RewardItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RewardItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RewardResp struct {
	PacketHead           *Ipacket      `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Item                 []*RewardItem `protobuf:"bytes,2,rep,name=item,proto3" json:"item,omitempty"`
	Victory              bool          `protobuf:"varint,3,opt,name=victory,proto3" json:"victory,omitempty"`
	Dvt                  int32         `protobuf:"varint,4,opt,name=dvt,proto3" json:"dvt,omitempty"`
	ShareDvt             int32         `protobuf:"varint,5,opt,name=shareDvt,proto3" json:"shareDvt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RewardResp) Reset()         { *m = RewardResp{} }
func (m *RewardResp) String() string { return proto.CompactTextString(m) }
func (*RewardResp) ProtoMessage()    {}
func (*RewardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{21}
}

func (m *RewardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardResp.Unmarshal(m, b)
}
func (m *RewardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardResp.Marshal(b, m, deterministic)
}
func (m *RewardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardResp.Merge(m, src)
}
func (m *RewardResp) XXX_Size() int {
	return xxx_messageInfo_RewardResp.Size(m)
}
func (m *RewardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardResp.DiscardUnknown(m)
}

var xxx_messageInfo_RewardResp proto.InternalMessageInfo

func (m *RewardResp) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *RewardResp) GetItem() []*RewardItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *RewardResp) GetVictory() bool {
	if m != nil {
		return m.Victory
	}
	return false
}

func (m *RewardResp) GetDvt() int32 {
	if m != nil {
		return m.Dvt
	}
	return 0
}

func (m *RewardResp) GetShareDvt() int32 {
	if m != nil {
		return m.ShareDvt
	}
	return 0
}

func init() {
	proto.RegisterType((*MovingReq)(nil), "cmessage.MovingReq")
	proto.RegisterType((*MovingResp)(nil), "cmessage.MovingResp")
	proto.RegisterType((*AttackReq)(nil), "cmessage.AttackReq")
	proto.RegisterType((*AttackResp)(nil), "cmessage.AttackResp")
	proto.RegisterType((*AttackSuccessResp)(nil), "cmessage.AttackSuccessResp")
	proto.RegisterType((*JumpReq)(nil), "cmessage.JumpReq")
	proto.RegisterType((*JumpResp)(nil), "cmessage.JumpResp")
	proto.RegisterType((*SkillShieldResp)(nil), "cmessage.SkillShieldResp")
	proto.RegisterType((*SkillThornsResp)(nil), "cmessage.SkillThornsResp")
	proto.RegisterType((*SkillDeformationResp)(nil), "cmessage.SkillDeformationResp")
	proto.RegisterType((*SkillImmuneResp)(nil), "cmessage.SkillImmuneResp")
	proto.RegisterType((*ReliveResp)(nil), "cmessage.ReliveResp")
	proto.RegisterType((*FlagReq)(nil), "cmessage.FlagReq")
	proto.RegisterType((*FlagResp)(nil), "cmessage.FlagResp")
	proto.RegisterType((*FlagSuccessResp)(nil), "cmessage.FlagSuccessResp")
	proto.RegisterType((*UseItemReq)(nil), "cmessage.UseItemReq")
	proto.RegisterType((*AddHpResp)(nil), "cmessage.AddHpResp")
	proto.RegisterType((*UseItem1003Resp)(nil), "cmessage.UseItem1003Resp")
	proto.RegisterType((*UpdateDvtResp)(nil), "cmessage.UpdateDvtResp")
	proto.RegisterType((*RewardReq)(nil), "cmessage.RewardReq")
	proto.RegisterType((*RewardItem)(nil), "cmessage.RewardItem")
	proto.RegisterType((*RewardResp)(nil), "cmessage.RewardResp")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6) }

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 1292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcd, 0x72, 0xdb, 0xd4,
	0x17, 0x1f, 0x49, 0x56, 0x6c, 0x1d, 0x27, 0x4d, 0xaa, 0x7f, 0xfe, 0xed, 0x25, 0x94, 0x62, 0x44,
	0x01, 0xf3, 0x95, 0xd6, 0x49, 0x77, 0x7c, 0xcc, 0x84, 0x66, 0x98, 0x86, 0x99, 0x32, 0x45, 0x49,
	0x37, 0x6c, 0x82, 0x2a, 0x5d, 0x3b, 0x9a, 0x58, 0x96, 0xaa, 0x7b, 0x65, 0x9a, 0x3c, 0x03, 0xac,
	0x58, 0xc0, 0x6b, 0xf0, 0x2a, 0x2c, 0xd8, 0xb1, 0xe3, 0x41, 0x98, 0x73, 0xae, 0xae, 0x25, 0x39,
	0x31, 0xcc, 0xb8, 0x66, 0x86, 0x55, 0xce, 0xef, 0xdc, 0x73, 0x75, 0xee, 0xf9, 0x3e, 0x0e, 0xac,
	0x67, 0xe3, 0xe0, 0x82, 0xe7, 0xbb, 0x59, 0x9e, 0xca, 0xd4, 0xed, 0x84, 0x09, 0x17, 0x22, 0x18,
	0xf1, 0x1d, 0x27, 0x2b, 0x9e, 0x2b, 0xa6, 0xf7, 0x9b, 0x01, 0xce, 0x93, 0x74, 0x1a, 0x4f, 0x46,
	0x3e, 0x7f, 0xe1, 0x0e, 0x00, 0x9e, 0x06, 0xe1, 0x39, 0x97, 0x8f, 0x79, 0x10, 0x31, 0xa3, 0x67,
	0xf4, 0xbb, 0x7b, 0x37, 0x77, 0xf5, 0xbd, 0xdd, 0xa3, 0x8c, 0x0e, 0xfd, 0x9a, 0x90, 0xeb, 0x42,
	0x6b, 0x98, 0xa7, 0x09, 0x33, 0x7b, 0x46, 0xdf, 0xf1, 0x89, 0x76, 0xb7, 0xc1, 0x16, 0xe7, 0xf1,
	0x78, 0xcc, 0xac, 0x9e, 0xd1, 0xb7, 0x7c, 0x05, 0xdc, 0x1b, 0x60, 0xca, 0x94, 0xb5, 0x48, 0xce,
	0x94, 0xa9, 0xbb, 0x0e, 0xc6, 0x4b, 0x66, 0xf7, 0x8c, 0xbe, 0xe9, 0x1b, 0x2f, 0x11, 0x5d, 0xb0,
	0x35, 0x85, 0x2e, 0x5c, 0x06, 0x6d, 0xba, 0x74, 0x14, 0xb1, 0x76, 0xcf, 0xe8, 0xdb, 0xbe, 0x86,
	0xee, 0x16, 0x58, 0x89, 0x18, 0xb1, 0x0e, 0x7d, 0x06, 0x49, 0xe4, 0x44, 0x71, 0xce, 0x1c, 0xba,
	0x8b, 0xa4, 0xf7, 0xa3, 0x05, 0xa0, 0x8d, 0x12, 0xd9, 0x32, 0x56, 0xa1, 0x05, 0x19, 0xe7, 0x11,
	0x99, 0x65, 0xfb, 0x0a, 0xb8, 0xf7, 0x60, 0x23, 0xe7, 0x51, 0x11, 0xf2, 0x63, 0x84, 0x27, 0xa2,
	0xb4, 0xaf, 0xc9, 0x74, 0xef, 0x80, 0x13, 0xc5, 0x39, 0x0f, 0x65, 0x9c, 0x4e, 0xc8, 0x5c, 0xd3,
	0xaf, 0x18, 0x68, 0xd9, 0xf3, 0x20, 0xcf, 0x63, 0x9e, 0x93, 0xed, 0xb6, 0xaf, 0x21, 0xea, 0x8c,
	0xe2, 0xcb, 0x4b, 0xe5, 0x05, 0xdb, 0x57, 0x00, 0xe5, 0x89, 0x38, 0x11, 0xda, 0x13, 0x25, 0x54,
	0xfe, 0xeb, 0x34, 0xfc, 0xe7, 0x68, 0xff, 0xed, 0x40, 0x47, 0xc8, 0x34, 0x7b, 0x92, 0x4e, 0x39,
	0x03, 0xba, 0x36, 0xc3, 0xee, 0x5d, 0x00, 0x4d, 0x9f, 0x08, 0xd6, 0x25, 0x13, 0x6a, 0x1c, 0xb7,
	0x07, 0xdd, 0x2c, 0x15, 0xcf, 0xb2, 0x28, 0x90, 0x28, 0xb0, 0x4e, 0x02, 0x75, 0x16, 0xc6, 0xbc,
	0x10, 0x3c, 0x67, 0x1b, 0x2a, 0xe6, 0x48, 0xa3, 0xc6, 0x61, 0x31, 0x09, 0xbf, 0x0e, 0x12, 0xce,
	0x6e, 0x10, 0x7f, 0x86, 0xbd, 0x3f, 0x0d, 0x70, 0x0e, 0xa4, 0x0c, 0xc2, 0xf3, 0xd5, 0x26, 0x59,
	0x9e, 0x16, 0x93, 0x88, 0x82, 0x60, 0xfb, 0x0a, 0x5c, 0x49, 0xb2, 0x59, 0x2a, 0xda, 0x65, 0x20,
	0x29, 0x15, 0x6b, 0xe9, 0xb5, 0xd6, 0x4c, 0x2f, 0x72, 0x6a, 0xbb, 0xe1, 0xd4, 0x8e, 0x76, 0xea,
	0x3a, 0x18, 0x97, 0xda, 0xc5, 0x97, 0x3a, 0x11, 0x61, 0x96, 0x88, 0xde, 0xcf, 0x26, 0x80, 0x36,
	0x73, 0xb9, 0xb4, 0xbb, 0xce, 0x4e, 0x65, 0x91, 0x75, 0xd5, 0xa2, 0xd6, 0x02, 0x8b, 0xec, 0xa6,
	0x45, 0xb7, 0x60, 0x4d, 0x9c, 0xc5, 0x7c, 0xac, 0x4d, 0x2d, 0x11, 0xf2, 0x63, 0x71, 0x7c, 0x1e,
	0x67, 0x65, 0x5e, 0x95, 0x08, 0xf5, 0x9d, 0x65, 0x64, 0xb4, 0xed, 0x9b, 0x67, 0x19, 0xca, 0x45,
	0x41, 0x12, 0x8c, 0x38, 0x99, 0x6e, 0xfb, 0x25, 0xc2, 0x80, 0x87, 0x79, 0x2c, 0xe3, 0x30, 0x18,
	0xeb, 0x14, 0xd3, 0x98, 0xde, 0xac, 0x53, 0xcb, 0x94, 0xc2, 0xfb, 0xdd, 0x80, 0x9b, 0xca, 0x33,
	0xc7, 0x45, 0x18, 0x72, 0x21, 0xfe, 0x4b, 0x0e, 0xa2, 0x90, 0xaf, 0x35, 0x42, 0xde, 0x6e, 0x84,
	0xbc, 0x33, 0x17, 0x72, 0xa7, 0x0a, 0xf9, 0x53, 0x68, 0x7f, 0x55, 0x24, 0xd9, 0xf2, 0x69, 0x4d,
	0x75, 0x64, 0x56, 0x75, 0xe4, 0x7d, 0x03, 0x1d, 0xf5, 0xc5, 0xa5, 0x1d, 0x74, 0xe5, 0x93, 0x3f,
	0x18, 0xb0, 0x79, 0x8c, 0xc6, 0x1e, 0x53, 0xe4, 0x57, 0xf8, 0xe9, 0x5a, 0x72, 0x59, 0x8d, 0xe4,
	0xc2, 0xfe, 0x43, 0xd4, 0x89, 0xa0, 0x30, 0x58, 0xfe, 0x0c, 0x57, 0xcf, 0x39, 0x39, 0x4b, 0xf3,
	0x89, 0x58, 0xf1, 0x73, 0x24, 0x7d, 0x54, 0x3f, 0x47, 0x21, 0x7c, 0x8e, 0xa2, 0xaa, 0xe7, 0x68,
	0xec, 0x15, 0xb0, 0x4d, 0xaf, 0x39, 0xe4, 0xc3, 0x34, 0x4f, 0x02, 0x6c, 0xd2, 0x2b, 0x7e, 0x52,
	0x10, 0x45, 0x07, 0xf2, 0x5c, 0x3f, 0x49, 0xa1, 0xca, 0x0b, 0x47, 0x49, 0x52, 0x4c, 0xf8, 0x8a,
	0x55, 0xc6, 0xf4, 0x51, 0xad, 0x52, 0x21, 0xf4, 0x82, 0xa2, 0x2a, 0x2f, 0x68, 0xec, 0xfd, 0xe1,
	0x00, 0xf8, 0x7c, 0x1c, 0x4f, 0x57, 0xfa, 0x92, 0xeb, 0x7b, 0xb4, 0x0b, 0xad, 0x2c, 0xc8, 0x65,
	0x59, 0x9f, 0x44, 0x63, 0x69, 0x9d, 0xc5, 0xaa, 0x34, 0x1d, 0x1f, 0x49, 0x94, 0x92, 0x17, 0x19,
	0x2f, 0xbb, 0x16, 0xd1, 0x38, 0xba, 0x22, 0x3e, 0x7c, 0xca, 0xf3, 0x90, 0x4f, 0x64, 0xd9, 0xb7,
	0x6a, 0x9c, 0x5a, 0xef, 0xb2, 0xa8, 0x77, 0xed, 0x40, 0xa7, 0xd0, 0x73, 0xcc, 0x51, 0x16, 0x6b,
	0xac, 0xca, 0x1e, 0x1a, 0x65, 0xdf, 0xd5, 0x65, 0x3f, 0x1b, 0xff, 0xeb, 0x7f, 0x3b, 0xfe, 0x37,
	0xfe, 0x71, 0xfc, 0xdf, 0xa0, 0xfb, 0xd7, 0x8f, 0xff, 0xcd, 0x05, 0xe3, 0x7f, 0x6b, 0xc1, 0xf8,
	0xbf, 0x49, 0xda, 0x66, 0xe3, 0xbf, 0x2a, 0x3d, 0x77, 0x61, 0xe9, 0xfd, 0xaf, 0x59, 0x7a, 0xb5,
	0xcc, 0xd8, 0x5e, 0x98, 0x19, 0xff, 0x6f, 0x66, 0x46, 0xad, 0xa6, 0x6e, 0x2d, 0xac, 0xa9, 0xdb,
	0xcd, 0x9a, 0x9a, 0x5b, 0x31, 0xd8, 0x95, 0x15, 0xa3, 0xbe, 0x9e, 0xbc, 0x36, 0xb7, 0x9e, 0xa8,
	0x82, 0x39, 0xe4, 0x43, 0xb6, 0x33, 0x2b, 0x98, 0x43, 0x3e, 0xc4, 0x3b, 0x8a, 0x3a, 0x11, 0xec,
	0x75, 0xa5, 0x4f, 0xe3, 0x5a, 0x91, 0xdd, 0xa9, 0x17, 0xd9, 0xfc, 0x2a, 0xf3, 0xc6, 0xd5, 0x55,
	0x86, 0xbc, 0x8e, 0x67, 0x77, 0xd5, 0xaa, 0x4a, 0x00, 0xbd, 0x1e, 0x8c, 0xc7, 0x07, 0x52, 0xe6,
	0xec, 0x4d, 0x15, 0xa5, 0x12, 0xd2, 0xb2, 0x39, 0x95, 0xac, 0x47, 0x5c, 0x24, 0x51, 0xf7, 0x88,
	0xcb, 0xc3, 0xa9, 0x64, 0x6f, 0x29, 0xdd, 0x0a, 0xd1, 0xdc, 0xe4, 0x02, 0xf9, 0x5e, 0x39, 0x37,
	0x09, 0x61, 0x5e, 0xd3, 0x74, 0x7a, 0x5b, 0xe5, 0x35, 0x0d, 0x27, 0x5a, 0x61, 0x39, 0xbb, 0x57,
	0x7e, 0x35, 0xe6, 0xc4, 0xc9, 0x04, 0x7b, 0xa7, 0xe4, 0x64, 0xc2, 0xf5, 0x60, 0x83, 0x26, 0xd6,
	0xe9, 0x60, 0xf0, 0x60, 0x70, 0x1a, 0x46, 0xec, 0x5d, 0x3a, 0xeb, 0x12, 0x13, 0x79, 0x8f, 0xa2,
	0x86, 0xcc, 0x1e, 0xca, 0xbc, 0xd7, 0x94, 0xd9, 0x9b, 0x93, 0xd9, 0x47, 0x99, 0x7e, 0x53, 0x66,
	0x7f, 0x4e, 0xe6, 0x21, 0xca, 0xbc, 0xdf, 0x94, 0x79, 0xf8, 0x28, 0x72, 0x7b, 0xb0, 0x1e, 0x4b,
	0x9e, 0x9c, 0x0e, 0x1e, 0x28, 0x55, 0x1f, 0xa8, 0x6a, 0x44, 0x1e, 0xb2, 0x9a, 0x12, 0xa4, 0xe8,
	0xc3, 0x86, 0xc4, 0x7e, 0x53, 0x82, 0xd4, 0x7c, 0xd4, 0x90, 0x40, 0x2d, 0xb7, 0xa1, 0xcd, 0x5f,
	0x14, 0x71, 0x76, 0x3a, 0x60, 0x1f, 0x2b, 0x37, 0x12, 0x1c, 0x54, 0x07, 0xfb, 0x6c, 0xb7, 0x76,
	0xb0, 0x8f, 0x11, 0x25, 0x8a, 0xdd, 0xef, 0x59, 0x58, 0x47, 0x04, 0xbc, 0x4f, 0xa1, 0xfd, 0xe5,
	0x38, 0x58, 0xf2, 0x47, 0x8e, 0xf7, 0x19, 0x74, 0xd4, 0xed, 0xa5, 0x5a, 0xa3, 0xf7, 0x8b, 0x01,
	0x9b, 0x78, 0xff, 0xd5, 0x97, 0x1f, 0xea, 0x9b, 0x66, 0xad, 0x6f, 0xde, 0x05, 0xc0, 0xbf, 0x03,
	0x11, 0xa6, 0xb9, 0xee, 0xf7, 0x35, 0x8e, 0x3e, 0xdf, 0x53, 0xe7, 0xad, 0xea, 0x5c, 0x71, 0xbc,
	0x9f, 0x0c, 0x80, 0x67, 0x82, 0x1f, 0x49, 0x9e, 0xac, 0x70, 0x37, 0xc7, 0x3e, 0x23, 0x79, 0x72,
	0x34, 0x5b, 0x0b, 0x14, 0xc2, 0xd8, 0x84, 0x69, 0x31, 0xd1, 0xad, 0x5f, 0x01, 0xbd, 0x56, 0xd9,
	0xd5, 0x5a, 0xf5, 0x1d, 0x38, 0x07, 0x51, 0xf4, 0x78, 0xe9, 0x2d, 0x48, 0xcd, 0x01, 0x73, 0x36,
	0x07, 0xb6, 0xc0, 0x0a, 0x22, 0xfd, 0x18, 0x24, 0xbd, 0x09, 0x6c, 0x96, 0x66, 0x63, 0x2a, 0xbe,
	0xba, 0x1e, 0xb5, 0x2b, 0xd7, 0xfa, 0x86, 0xd5, 0xe8, 0x1b, 0xde, 0x4b, 0xd8, 0x50, 0x3d, 0xe7,
	0x70, 0x2a, 0xff, 0xcd, 0xe5, 0x77, 0x0b, 0xac, 0x11, 0xd7, 0xfe, 0x45, 0xd2, 0xfb, 0x1c, 0x1c,
	0x9f, 0x7f, 0x1f, 0xe4, 0xd1, 0x92, 0xb9, 0xbf, 0x87, 0x8b, 0x01, 0xde, 0x47, 0x67, 0xa1, 0xbe,
	0x58, 0x5d, 0xb4, 0x7d, 0x33, 0xae, 0x45, 0xd4, 0xac, 0x45, 0xd4, 0xfb, 0xd5, 0xd0, 0x97, 0x96,
	0xb5, 0xb5, 0x0f, 0x2d, 0xcc, 0x19, 0x66, 0xf6, 0xac, 0x7e, 0x77, 0x6f, 0xbb, 0x12, 0xae, 0xde,
	0xe2, 0x93, 0x04, 0xfa, 0x7c, 0x1a, 0x87, 0x32, 0xcd, 0x2f, 0xc8, 0x0d, 0x1d, 0x5f, 0x43, 0xdd,
	0xab, 0x5b, 0x55, 0xaf, 0xa6, 0xd9, 0x18, 0xe4, 0x18, 0x84, 0xf2, 0x57, 0xc0, 0x0c, 0x7f, 0xb1,
	0xf1, 0x6d, 0x77, 0xf7, 0xfe, 0x27, 0x5a, 0xcf, 0xf3, 0x35, 0xfa, 0xff, 0xc8, 0xfe, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xca, 0x44, 0xf9, 0xaa, 0x44, 0x11, 0x00, 0x00,
}
