// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pub.proto

package cmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//客户端包头
type Ipacket struct {
	Stx                  int32     `protobuf:"varint,1,opt,name=Stx,proto3" json:"Stx,omitempty"`
	Ckx                  int32     `protobuf:"varint,2,opt,name=Ckx,proto3" json:"Ckx,omitempty"`
	Id                   MessageID `protobuf:"varint,3,opt,name=Id,proto3,enum=cmessage.MessageID" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Ipacket) Reset()         { *m = Ipacket{} }
func (m *Ipacket) String() string { return proto.CompactTextString(m) }
func (*Ipacket) ProtoMessage()    {}
func (*Ipacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0615d3bf98f7d855, []int{0}
}

func (m *Ipacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipacket.Unmarshal(m, b)
}
func (m *Ipacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipacket.Marshal(b, m, deterministic)
}
func (m *Ipacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipacket.Merge(m, src)
}
func (m *Ipacket) XXX_Size() int {
	return xxx_messageInfo_Ipacket.Size(m)
}
func (m *Ipacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipacket.DiscardUnknown(m)
}

var xxx_messageInfo_Ipacket proto.InternalMessageInfo

func (m *Ipacket) GetStx() int32 {
	if m != nil {
		return m.Stx
	}
	return 0
}

func (m *Ipacket) GetCkx() int32 {
	if m != nil {
		return m.Ckx
	}
	return 0
}

func (m *Ipacket) GetId() MessageID {
	if m != nil {
		return m.Id
	}
	return MessageID_MSG_BEGIN
}

//心跳包
type HeartPacket struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartPacket) Reset()         { *m = HeartPacket{} }
func (m *HeartPacket) String() string { return proto.CompactTextString(m) }
func (*HeartPacket) ProtoMessage()    {}
func (*HeartPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0615d3bf98f7d855, []int{1}
}

func (m *HeartPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartPacket.Unmarshal(m, b)
}
func (m *HeartPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartPacket.Marshal(b, m, deterministic)
}
func (m *HeartPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartPacket.Merge(m, src)
}
func (m *HeartPacket) XXX_Size() int {
	return xxx_messageInfo_HeartPacket.Size(m)
}
func (m *HeartPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartPacket.DiscardUnknown(m)
}

var xxx_messageInfo_HeartPacket proto.InternalMessageInfo

func (m *HeartPacket) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PlayerData struct {
	PlayerID             int64    `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`
	PlayerGold           int32    `protobuf:"varint,3,opt,name=PlayerGold,proto3" json:"PlayerGold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0615d3bf98f7d855, []int{2}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerID() int64 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *PlayerData) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerData) GetPlayerGold() int32 {
	if m != nil {
		return m.PlayerGold
	}
	return 0
}

func init() {
	proto.RegisterType((*Ipacket)(nil), "cmessage.Ipacket")
	proto.RegisterType((*HeartPacket)(nil), "cmessage.HeartPacket")
	proto.RegisterType((*PlayerData)(nil), "cmessage.PlayerData")
}

func init() { proto.RegisterFile("pub.proto", fileDescriptor_0615d3bf98f7d855) }

var fileDescriptor_0615d3bf98f7d855 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x28, 0x4d, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95,
	0xe2, 0xce, 0x2d, 0x4e, 0xcf, 0x4c, 0x81, 0x08, 0x2b, 0x05, 0x71, 0xb1, 0x7b, 0x16, 0x24, 0x26,
	0x67, 0xa7, 0x96, 0x08, 0x09, 0x70, 0x31, 0x07, 0x97, 0x54, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x81, 0x98, 0x20, 0x11, 0xe7, 0xec, 0x0a, 0x09, 0x26, 0x88, 0x88, 0x73, 0x76, 0x85, 0x90,
	0x32, 0x17, 0x93, 0x67, 0x8a, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0xb0, 0x1e, 0xcc, 0x48,
	0x3d, 0x5f, 0x08, 0xed, 0xe9, 0x12, 0xc4, 0xe4, 0x99, 0xa2, 0xa4, 0xc8, 0xc5, 0xed, 0x91, 0x9a,
	0x58, 0x54, 0x12, 0x00, 0x31, 0x57, 0x88, 0x8b, 0xa5, 0x24, 0x33, 0x37, 0x15, 0x6c, 0x30, 0x73,
	0x10, 0x98, 0xad, 0x94, 0xc1, 0xc5, 0x15, 0x90, 0x93, 0x58, 0x99, 0x5a, 0xe4, 0x92, 0x58, 0x92,
	0x28, 0x24, 0xc5, 0xc5, 0x01, 0xe1, 0x79, 0xba, 0x40, 0x55, 0xc1, 0xf9, 0x42, 0x72, 0x30, 0x95,
	0x7e, 0x89, 0xb9, 0xa9, 0x60, 0xa7, 0x70, 0x06, 0x21, 0x89, 0x20, 0xe4, 0xdd, 0xf3, 0x73, 0x20,
	0x2e, 0x63, 0x0d, 0x42, 0x12, 0x71, 0xe2, 0x8d, 0xe2, 0xd6, 0xd3, 0xb7, 0x86, 0xb9, 0x34, 0x89,
	0x0d, 0xec, 0x6d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xd7, 0x68, 0x39, 0x1a, 0x01,
	0x00, 0x00,
}
